// Database of official Benin Communes and their corresponding Districts/Neighborhoods.
// Generated from the official Benin administrative division database.

const Map<String, List<String>> beninLocations = {
  'Abomey': [
    'Adandokpodji',
    'Agblome',
    'Agbodjannangan',
    'Agbokpa',
    'Agnangnan',
    'Ahouaga',
    'Akouessa',
    'Allomakanme',
    'Azali',
    'Detohou',
    'Detohou Centre',
    'Dilikotcho',
    'Djegbe',
    'Djime',
    'Dogueme',
    'Dokon',
    'Dota',
    'Gbecon-Houegbo',
    'Gbehizankon',
    'Gbekon Hounli',
    'Gnansata',
    'Goho',
    'Gueguezogon',
    'Houao',
    'Houeli',
    'Hounli',
    'Hountondji',
    'Kodji Centre',
    'Legbaholi',
    'Lele',
    'Lokokanme',
    'Oueme',
    'Sada',
    'Sehoun',
    'Sogbo-Aliho',
    'Sohoue',
    'Sonou Akouta',
    'Sonou Fiye',
    'Tohizanly',
    'Vekpa',
    'Vidole',
    'Wankon',
    'Wo-Tangadji',
    'Zassa',
    'Zounzonme',
  ],
  'Abomey-Calavi': [
    'Abikouholi',
    'Abomey-Calavi',
    'Adjagbo',
    'Adjagbo-Aidjedo',
    'Adjaglo-Aidjedo',
    'Adjame',
    'Adjogansa',
    'Adovie',
    'Agamandin',
    'Agassa-Godomey',
    'Agbo-Codji-Sedegbe',
    'Agongbe',
    'Agonkanmey',
    'Agonkessa',
    'Agonme',
    'Agonsoundja',
    'Agori',
    'Ahossougbeta',
    'Ahouato',
    'Aifa',
    'Aimevo',
    'Aitchedji',
    'Akassato',
    'Akassato Centre',
    'Akossavie',
    'Alansankome',
    'Aledjo',
    'Alegleta',
    'Alladacome',
    'Amanhoun',
    'Anagbo',
    'Assrossa',
    'Atrokpo-Codji',
    'Avagbe',
    'Azonsa',
    'Bozoun',
    'Cite La Victoire',
    'Cite Les Palmiers',
    'Cococodji',
    'Cocotomey',
    'Dangbodji',
    'Dassekomey',
    'Dekoungbe-Eglise',
    'Dekoungbe-Usine',
    'Denou',
    'Dessato',
    'Djekpota',
    'Djigbo',
    'Djissoukpa',
    'Djoukpa-Togoudo',
    'Dokomey',
    'Domey-Gbo',
    'Dossounou',
    'Drabo',
    'Fandji',
    'Fifonsi',
    'Fignonhou',
    'Finafa',
    'Ganganzounme',
    'Gbegnigan-Midokpo',
    'Gbetagbo',
    'Gbodje',
    'Gbodje-Womey',
    'Gbodjo',
    'Gbodjoko',
    'Glo-Tokpa',
    'Gninkindji',
    'Godomey',
    'Godomey-N\'gbeho',
    'Godomey-Togoudo',
    'Golo-Djigbe',
    'Golo-Fanto',
    'Hadjanaho',
    'Hedome',
    'Helouto',
    'Hevie',
    'Hevie Centre',
    'Houakomey',
    'Houegoudo',
    'Houeke-Gbo',
    'Houeke-Honou',
    'Houeto',
    'Houinme',
    'Hounsa-Agbodokpa',
    'Hounyeva',
    'Hounzevie',
    'Kansounkpa',
    'Koletin',
    'Kpanroun',
    'Kpanroun-Dodomey',
    'Kpaviedja',
    'Kpe',
    'Kpodji-Les-Monts',
    'Kpossidja',
    'Kpotomey',
    'La Paix',
    'Lobozounkpa',
    'Lohoussa',
    'Maria-Gleta',
    'Missebo-Espace Saint',
    'Missessinto',
    'Ningboto',
    'Nonhouenou',
    'Ouedo',
    'Ouedo Centre',
    'Ouega-Ague',
    'Ouega-Tokpa',
    'Ounvenoumede',
    'Plateau',
    'Salamey',
    'Sedjannanko',
    'Sedomey',
    'Seloli-Fandji',
    'Seme',
    'Sodo',
    'Sogan',
    'Sokan',
    'Some',
    'Tankpe',
    'Tchinangbegbo',
    'Togba',
    'Togba Maria-Gleta',
    'Togbin-Daho',
    'Togbin-Kpevi',
    'Tognin-Fandji',
    'Tokan',
    'Tokan Aidegnon',
    'Tokpa',
    'Tokpa-Zoungo',
    'Tokpa-Zoungo Nord',
    'Tokpa-Zoungo Sud',
    'Wawata',
    'Wawata-Todja',
    'Womey Centre',
    'Yekon-Aga',
    'Yekon-Do',
    'Yenandjro',
    'Yevie',
    'Yevie-Nougo',
    'Yolomahouto',
    'Zekanmey',
    'Zekanmey-Dome',
    'Zinvie',
    'Zinvie-Agoledji',
    'Zinvie-Fandji',
    'Zinvie-Zounme',
    'Zogbadje',
    'Zopah',
    'Zopah Palmeraie',
    'Zoundja',
    'Zounga',
    'Zoungo',
  ],
  'Adja-Ouere': [
    'Abadago',
    'Adja-Ouere',
    'Adjaglo',
    'Adjegounle',
    'Adjelemide',
    'Adjoda',
    'Affacha',
    'Affesseda',
    'Attan-Ewe',
    'Attan-Ouignan-Ayetedjou',
    'Ayeladjou',
    'Dagbla',
    'Danhime',
    'Djidagba',
    'Dogbo',
    'Egbe',
    'Egbe-Agbo',
    'Fouditi',
    'Gbagbata',
    'Gbanou',
    'Houedame',
    'Houeli-Gaba',
    'Ichougbo',
    'Igba',
    'Igbo-Aidin',
    'Igbo-Akporo',
    'Igbo-Ikoko',
    'Igbo-Iroko',
    'Igbo-Oro',
    'Ikpinle',
    'Ikpinle-Itaraka',
    'Ikpinle-Sekanme',
    'Ikpinle-Yenawa',
    'Ilako-Abiala',
    'Imoro',
    'Ita Aholou',
    'Ita-Aro',
    'Ita-Bolarinwa',
    'Ita-Egbebi',
    'Ita-Egbebi-Alakparou',
    'Ita-Ogou',
    'Itchagba-Gbadodo',
    'Itchangni',
    'Itchede',
    'Iwinka',
    'Iwoye-Oko-Igbo',
    'Kadjola',
    'Kokorokehoun',
    'Kpoulou',
    'Kpoulou-Idi-Ekpe',
    'Kpoulou-Itchougan',
    'Logou',
    'Masse',
    'Masse-Adjegounle',
    'Missebo',
    'Mowobani',
    'Obanigbe-Fouditi',
    'Obeke-Ouere',
    'Ogoukpate',
    'Ogouro',
    'Oke-Odan',
    'Oke-Odo',
    'Oke-Ola',
    'Oko-Akare',
    'Oko-Djeguede',
    'Okoffin',
    'Ologo',
    'Ologo Akpakpa',
    'Olohoungbodje',
    'Ouignan-Gbadodo',
    'Owochande',
    'Tatonnonkon',
    'Tatonnonkon Jardin',
    'Teffi-Okeigbala',
    'Toffo',
    'Towi',
    'Trobossi',
  ],
  'Adjarra': [
    'Adjarra 1',
    'Adjarra 2',
    'Adjati-Djogbehoue',
    'Adjati-Vedo',
    'Adjinan',
    'Adjinan-Aga',
    'Adovie',
    'Adovie Alaga',
    'Agaougbeta',
    'Agata',
    'Agbomey-Takplikpo',
    'Agboto',
    'Aglogbe',
    'Ahouandji',
    'Alladako',
    'Alladako-Degoeto',
    'Anagbo',
    'Ayihounzo',
    'Bokovi-Tchaka',
    'Djavi',
    'Djavi-Zebe',
    'Djevie -Wadon',
    'Do-Hongla',
    'Dossouvie',
    'Drogbo',
    'Gassako',
    'Gbangnito',
    'Gbehamey',
    'Hahame',
    'Hevie-Kpota',
    'Honvie',
    'Honvie Centre',
    'Houegbo',
    'Hounhoueko',
    'Hounsa-Assiogbossa',
    'Hounsinvie',
    'Hounve',
    'Kpadovie',
    'Kpota',
    'Kpovie-Gbada',
    'Lindja-Dangbo',
    'Malanhoui',
    'Malanhoui-Kpodo',
    'Mededjonou',
    'Mededjonou-Gbehadji',
    'Oueke',
    'Sedje',
    'Sedje-Gbeta',
    'Seme',
    'Sota',
    'Sota-Tcheme',
    'Tanme',
    'Tchakou',
    'Tokome',
    'Vidjinan',
    'Yevie',
  ],
  'Adjohoun': [
    'Abato',
    'Abeokouta',
    'Abidomey',
    'Adjohoun',
    'Agbakon',
    'Agbossa-Adjakahoue',
    'Agonlin',
    'Ague-Milahin',
    'Ahlan',
    'Ahouandjannafon',
    'Akouehan-Tohoue',
    'Akpadanou',
    'Allandohou',
    'Allanzounme',
    'Assigui-Gbongodo',
    'Assrossa',
    'Awogoudo',
    'Awonou',
    'Azowlisse',
    'Dannou',
    'Dannou Ayidagbedji',
    'Dekanme',
    'Deme',
    'Deme Centre',
    'Fanvi',
    'Fonly',
    'Gangban',
    'Gangban Toganhounsa',
    'Gbada',
    'Gbada Kpota',
    'Gbannan',
    'Gbedogo-Oudanou',
    'Gbegbessa',
    'Gbekandji',
    'Gla',
    'Gogbo',
    'Gounouhoue',
    'Goutin',
    'Hlankpa',
    'Houeda',
    'Houedo-Ague',
    'Houedo-Wo',
    'Houekpa-Kpota',
    'Houinsa',
    'Houssa',
    'Kadebou-Zounme',
    'Kakanitchoe',
    'Kindji-Aname',
    'Klogbomey',
    'Kode',
    'Kode - Akpo',
    'Kode-Ague',
    'Kode-Gouke',
    'Kpatinsa',
    'Kpodedji',
    'Kpota',
    'Lokossa',
    'Lowe',
    'Saoro',
    'Sekondji',
    'Siliko',
    'Sissekpa',
    'Sokpetinkon',
    'Tode',
    'Togbota',
    'Togbota-Ague',
    'Togbota-Oujra',
    'Wadon',
    'Zoungbome',
    'Zoungodo',
  ],
  'Agbangnizoun': [
    'Abigo',
    'Adanhondjigo',
    'Adanhondjigon',
    'Adingnigon',
    'Adjido',
    'Agbangnizoun',
    'Agbidime',
    'Ahissatogon',
    'Ahouakanme',
    'Akodebakou',
    'Akpeho-Dokpa',
    'Akpeho-Seme',
    'Avali',
    'Azankpanto',
    'Azozoundji',
    'Danli',
    'Dekanme',
    'Dilly-Fanou',
    'Dodji',
    'Dodome',
    'Fonli',
    'Gbindounme',
    'Gboli',
    'Gbozoun 1',
    'Gbozoun 2',
    'Gnizinta',
    'Hagbladou',
    'Hodja',
    'Houala',
    'Houndo',
    'Hounto',
    'Kanzoun',
    'Kinta',
    'Kpatinme',
    'Kpodji',
    'Kpota',
    'Kpoto',
    'Lego',
    'Lissazounme',
    'Loukpe',
    'Makpehogon',
    'Mignonhito',
    'Oungbenoudo',
    'Sahe',
    'Sekidjato',
    'Sinwe',
    'Sohoue-Dovota',
    'Tangoudo',
    'Tanta',
    'Tanve',
    'Tokpa',
    'Tossota',
    'Toweta',
    'Wedje',
    'Zoungbo-Gblome',
    'Zoungoudo',
    'Zoungoundo',
    'Zounme',
  ],
  'Aguegues': [
    'Agbodjedo',
    'Aholoukome',
    'Akodji',
    'Akpadon',
    'Akpakome',
    'Akpoloukome',
    'Aniviekome',
    'Avagbodji',
    'B\'mbe Akpa',
    'Be\'mbe',
    'Djekpe',
    'Djigbekome',
    'Dogodo',
    'Donoukpa',
    'Gbodje',
    'Goussa',
    'Houedome',
    'Houinta',
    'Kindji',
    'Kintokome',
    'Sohekome',
    'Somayi',
    'Trankome',
    'Woundekome',
    'Zinviekome',
    'Zoungame',
  ],
  'Akpro-Misserete': [
    'Abogome',
    'Abogome-Hlihoue',
    'Agondozoun',
    'Agondozoun Tanme',
    'Ahouandji',
    'Akpakanme',
    'Akpro-Hanzounme',
    'Akpro-Misserete',
    'Allagba',
    'Amouloko',
    'Anianlin',
    'Blehouan',
    'Danme-Lokonon',
    'Danto',
    'Danto Les Palmiers',
    'Ganmi',
    'Gbakpo-Sedje',
    'Gbedji',
    'Gome-Doko',
    'Gome-Sota',
    'Gouako-Kotoclome',
    'Houezounme-Daho',
    'Houezounme-Kpevi',
    'Hounli',
    'Katagon',
    'Kiliti',
    'Koudjannada',
    'Kouve',
    'Kpanou-Kpade',
    'Kpogon',
    'Kpole',
    'Ouiya',
    'Sogbe-Aligo',
    'Sohomey',
    'Tanme',
    'Tchian',
    'Tchoukou-Kpevi',
    'Tohouikanme',
    'Tokpa-Houete',
    'Vakon',
    'Vakon-Adanhou',
    'Vakon-Agatha',
    'Vakon-Anago',
    'Vakon-Azohoue',
    'Vakon-Gbo',
    'Vakon-Kpozoungo',
    'Vante',
    'Wayi-Sogbe',
    'Zoundji',
    'Zoungbome',
    'Zoungbome Kpadjrakanme',
  ],
  'Allada': [
    'Acclohoue',
    'Adimale',
    'Adjadangan',
    'Adjadji-Atinkousa',
    'Adjadji-Bata',
    'Adjadji-Cossoe',
    'Adjadji-Zoungbomey',
    'Adjohoun',
    'Adjrakandji',
    'Agbandonou',
    'Agbanou',
    'Agbantokpa',
    'Agondokpoe',
    'Agongblamey',
    'Ahito',
    'Ahota',
    'Ahouannonzoun',
    'Aligoudo',
    'Allada Centre',
    'Allomey',
    'Aota',
    'Assihoui',
    'Attogon',
    'Attogon Centre',
    'Attotinga',
    'Attouhonou',
    'Avakpa',
    'Avankamey',
    'Avazounkpa',
    'Ayakpata',
    'Ayame',
    'Ayou',
    'Azohoue-Gbedjicome',
    'Azohoue-Hongbo',
    'Bawekanmey',
    'Boli',
    'Dagleta',
    'Dahsramey',
    'Djohoungbonou',
    'Dodji-Aliho',
    'Dodjidangban',
    'Dodomey',
    'Dogoudo',
    'Dogoudo Ceg',
    'Donou',
    'Dovenou',
    'Dovo',
    'Gandaho',
    'Gbedji',
    'Gbegamey',
    'Gbeova',
    'Gbeta',
    'Gbeto',
    'Gbowele',
    'Glotomey',
    'Gounontomey',
    'Goussikpota',
    'Govie',
    'Hanafin',
    'Hangnan',
    'Hedjannansoun',
    'Hessa',
    'Hetin',
    'Hinvi',
    'Hollansatin',
    'Houegoudo',
    'Houinbatin',
    'Houkpokpoue',
    'Houndadja',
    'Houngbado',
    'Hounkpa',
    'Kotovi',
    'Kpodjava',
    'Kpodji',
    'Kpoguetomey',
    'Lanmandji',
    'Lissegazoun',
    'Lokokpa',
    'Lon-Agonmey',
    'Loto-Denou',
    'Migbehoue',
    'Niaouli',
    'Nouzounkpa',
    'Sebo',
    'Sehe',
    'Sehounsa',
    'Sekou',
    'Sohoun',
    'Sokoudenou',
    'Solokoue',
    'Soyo',
    'Tanga',
    'Tanga-Todo',
    'Tanmey',
    'Tegbo',
    'Togazoun',
    'Togo',
    'Togoudo',
    'Tokpa',
    'Tokpa-Avagoudo',
    'Tokpota',
    'Vehoui',
    'Wadon',
    'Wedjame',
    'Wibatin',
    'Winyikpa',
    'Wogo',
    'Yaahoue',
    'Zebou',
    'Zindagba',
    'Zoungbodji',
    'Zoungbomey',
    'Zoungoudo',
    'Zounledji',
    'Zounme-Aga',
    'Zounta',
  ],
  'Aplahoue': [
    'Aboloume',
    'Adame',
    'Adandehoue',
    'Aflantan',
    'Agbannate',
    'Agbotavou',
    'Agnamey',
    'Agodogoui',
    'Akeme',
    'Aplahoue',
    'Atomey',
    'Atomey-Aveganmey',
    'Atto-Houe',
    'Avegodo',
    'Avegodoui',
    'Avetuimey',
    'Azondogahoue',
    'Azove',
    'Azove Centre',
    'Badjame',
    'Bavou',
    'Bayame',
    'Bogandji',
    'Bossouhoue',
    'Bozinkpe',
    'Couffokpa',
    'Dannouhoue',
    'Datcha',
    'Dekandji',
    'Dekanmey',
    'Dekpo-Centre',
    'Dhossouhoue',
    'Djikpame',
    'Djimadohoue',
    'Djowe',
    'Dogohoue',
    'Donoume',
    'Dousso',
    'Edehoue',
    'Eglime',
    'Ekinhoue',
    'Fandjigahoue',
    'Gadekohounhoue',
    'Gbakonou',
    'Gbetohoue',
    'Gbeze',
    'Gblofoly',
    'Gnonfihoue',
    'Godohou',
    'Gougouta',
    'Havou',
    'Hedjinnawa',
    'Heletoumey',
    'Hessouhoue',
    'Hevi',
    'Hevi-Senouhoue',
    'Hoky',
    'Hontonmey',
    'Hontonou',
    'Hontoui',
    'Houetan',
    'Houngbamey',
    'Hounsahoue',
    'Kaitemey',
    'Kidji',
    'Kissamey',
    'Kogbetohoue',
    'Koumakohoue',
    'Koyohoue',
    'Kpakomey',
    'Kpodji',
    'Lagbave',
    'Lanhouetomey',
    'Lokogba',
    'Lokossouhoue',
    'Lonkly',
    'Mahougbehoue',
    'Ouchihoue',
    'Sehonouhoue',
    'Sinlita',
    'Sodjagohoue',
    'Takpatchiome',
    'Tannou',
    'Tchatehoue',
    'Tchiglihoue',
    'Totchikeme',
    'Touvou',
    'Vivimey',
    'Volly-Latadji',
    'Wakpe',
    'Yehouemey',
    'Zame',
    'Zohoudji',
  ],
  'Athieme': [
    'Abloganme',
    'Adame',
    'Adankpossi',
    'Adanlokpe',
    'Adhame',
    'Adjassinhoun-Condji',
    'Adjove',
    'Adohoun',
    'Agbedranfo',
    'Agbobada',
    'Agbogbomey',
    'Agniwedji',
    'Aguidahoue',
    'Ahoho',
    'Akonana',
    'Allounkoui',
    'Anatohoue',
    'Assedji-Agonsa',
    'Assedji-Daho',
    'Assekome',
    'Atchannou',
    'Atchontoe',
    'Athieme',
    'Athiemegan',
    'Avedji',
    'Avegodo',
    'Awakou',
    'Awame-Agbovedji',
    'Awame-Kponou',
    'Ayoucome',
    'Azonlihoue',
    'Bocohoue',
    'Condji-Agname',
    'Dedekpoe',
    'Dekpoe',
    'Devedodji',
    'Deveme',
    'Don-Agbodougbe',
    'Don-Kondji',
    'Donon',
    'Gbedji',
    'Gbehossou-Kponou',
    'Gleta',
    'Goudon',
    'Hahame',
    'Hokpame',
    'Houegle',
    'Hounkpon',
    'Kodji',
    'Kodji Kponou',
    'Konouhoue',
    'Koundohounhoue',
    'Kpinnou',
    'Kpodji',
    'Madeboui',
    'Sazouekpa',
    'Sazue Kpota',
    'Sevotinou',
    'Tadocome',
    'Tchicomey',
    'Togblo',
    'Toguido',
    'Zindonou',
    'Zounhoue Kpakpassa',
  ],
  'Avrankou': [
    'Affandji-Tanme',
    'Affomadje-Kada',
    'Agamadin',
    'Agbomasse',
    'Ahovo',
    'Alawa',
    'Atchoukpa',
    'Avaligbo',
    'Avrankou',
    'Bokousso',
    'Dangbodji',
    'Danme-Kpossou',
    'Danme-Tovihoudji',
    'Djomon',
    'Gbagla-Ganfan',
    'Gbagla-Ganfan Flonou',
    'Gbagla-Koke',
    'Gbakpo-Acle',
    'Gbakpo-Yenou',
    'Gbegodo',
    'Gbetchou',
    'Gbodje',
    'Gbohoungbo',
    'Gbozoume',
    'Gbozounme',
    'Hehoun',
    'Houedakome',
    'Houeli',
    'Houeze',
    'Houndome-Aligo',
    'Houngo',
    'Houngon-Djinon',
    'Kate-Kliko',
    'Kogbome',
    'Kotan',
    'Kouti',
    'Kouti- Logon',
    'Kouti-Karo',
    'Kouti-Yenawa',
    'Latche-Houezounme',
    'Loko-Dave',
    'Lotin-Gbedjehouin',
    'Lotin-Gbegodo',
    'Male',
    'Male-Houngo',
    'Ouanho',
    'Ouindodji',
    'Sado',
    'Sedje',
    'Sedje-Ahovo',
    'Sekanme',
    'Seligon',
    'Tanzoun',
    'Tanzoun Bliguede',
    'Tchakla',
    'Tchoukou-Daho',
    'Todedji',
    'Tokpa-Yonhossou',
    'Tokpo',
    'Vagnon',
    'Vodenou',
    'Wamon',
    'Zoungue',
  ],
  'Banikoara': [
    'Arbonga',
    'Atabenou',
    'Aviation',
    'Banikoara',
    'Batran',
    'Bofounou',
    'Bonhanrou',
    'Boniki',
    'Bonkere',
    'Bonni',
    'Bonte',
    'Bonyangou',
    'Bourin',
    'Demanou',
    'Derou Garou',
    'Domboure',
    'Domboure-Gah',
    'Dondagou',
    'Founougo',
    'Founougo-Boutera',
    'Founougo-Gah',
    'Founougo-Gorobani',
    'Gama',
    'Gamarou',
    'Gamere-Zongo',
    'Gbangbanga',
    'Gbassa',
    'Gbeniki',
    'Glegbabi',
    'Gnambanou',
    'Gnambourankorou',
    'Gnandarou',
    'Gomparou',
    'Gomparou Goussinrou',
    'Gomparou-Gokpadou',
    'Gougnirou',
    'Gougnirou-Gah',
    'Goumori',
    'Goumori-Bayedou',
    'Goumori-Gah',
    'Goumori-Gbissarou',
    'Goure-Ede',
    'Guiguiri',
    'Guimbagou',
    'Guinningou-Gah',
    'Iboto',
    'Igrigou',
    'Kakourogou',
    'Kali',
    'Kanderou',
    'Kanderou-Kotchera',
    'Kegamorou',
    'Kihouhou',
    'Kingarou',
    'Kokey',
    'Kokey-Filo',
    'Kokey-Sinakparou',
    'Kokiborou',
    'Kokire',
    'Kommon',
    'Koney',
    'Kori Guiguiri',
    'Kpagaguedou',
    'Kpako-Gbabi',
    'Kpeborogou',
    'Kpessanrou',
    'Mekrou',
    'Mondoukoka',
    'Mondoukoka-Gah',
    'Niekoubanta',
    'Nimbere',
    'Orou Gnonrou',
    'Ounet',
    'Ounet-Gah',
    'Ounet-Sekogbaourou',
    'Ounet-Sinakparou',
    'Pampime',
    'Piguire',
    'Pogoussorou',
    'Poto',
    'Poto-Gah',
    'Sakassinnou',
    'Samanga',
    'Sampeto',
    'Satouba',
    'Simperou',
    'Simperou-Gah',
    'Sionkpekoka',
    'Sirikou',
    'Sissianganrou',
    'Siwougourou',
    'Somperoukou',
    'Somperoukou-Gah',
    'Somperoukou-Gbessara',
    'Somperoukou-Yorounon',
    'Sonnou',
    'Sonnou-Gah',
    'Sonwari',
    'Soroko',
    'Soroko Gah',
    'Soroko Yorounon',
    'Soudou',
    'Sounsoun',
    'Tiganson',
    'Tihoure',
    'Tintinmou',
    'Tintinmou-Gah',
    'Tokey-Banta',
    'Toura',
    'Toura Gah',
    'Toura-Bio N\'worou',
    'Toura-Yokparou',
    'Wagou',
    'Weterou',
    'Yadikparou',
    'Yamberou',
    'Yangueri',
    'Yinyinpogou',
    'Yossinande',
  ],
  'Bante': [
    'Adjante',
    'Adjigo',
    'Agbon',
    'Agongni',
    'Agoua',
    'Akpaka',
    'Akpassi',
    'Aletan',
    'Aloba',
    'Assaba',
    'Atokolibe',
    'Ayigbo-Koto',
    'Banon',
    'Bante',
    'Basson',
    'Bobe',
    'Cloubou',
    'Djagballo',
    'Djero',
    'Ela-Meta',
    'Fomon',
    'Galata',
    'Galata-Igberi',
    'Gbedje',
    'Gbegamey',
    'Gotcha',
    'Gouka',
    'Idi-Ogou',
    'Illagbo',
    'Illare',
    'Illelakoun',
    'Issale',
    'Itchocobo',
    'Kadjogbe',
    'Kafegnigbe',
    'Kamala-Idjou',
    'Koko',
    'Kotakpa',
    'Lougba',
    'Malomi',
    'Mamatchoke',
    'Mayamon',
    'Montewo-Atake-Agbado',
    'N\'tchoche',
    'N\'tchon',
    'Odjogbile',
    'Oguede',
    'Oke-Kagoure',
    'Okoto',
    'Okouta-Oro',
    'Okouta-Osse',
    'Pira',
    'Sako',
    'Soula',
    'Zongo',
  ],
  'Bassila': [
    'Adjimon',
    'Adjiro',
    'Akarade',
    'Aledjo',
    'Aoro-Lokpa',
    'Aoro-Nago',
    'Appi',
    'Assion',
    'Awo',
    'Bassila',
    'Bassila Abiguedou',
    'Bassila Allan',
    'Bassila Bakabaka',
    'Bayakou',
    'Biguina Akpassa',
    'Biguina Holoude',
    'Biguina Tosso',
    'Bodi',
    'Boutou',
    'Diepani-Balimboli',
    'Dingou',
    'Dogue',
    'Frignion',
    'Guiguisso',
    'Igadougou',
    'Igbere',
    'Igbomako',
    'Kadegue',
    'Kaoute',
    'Kikele',
    'Kodowari',
    'Koiwali',
    'Kprekete',
    'Manigri',
    'Manigri Oke Igboele',
    'Manigri-Ikanni',
    'Manigri-Oke Souangbe',
    'Melan',
    'Modogui',
    'Nagayile',
    'Nibadara',
    'Nioro-Kolina',
    'Ouli',
    'Partago',
    'Penelan',
    'Penessoulou',
    'Salmanga',
    'Taba',
    'Tchetou',
    'Tchimberi',
    'Teke-Terou',
    'Wannou',
    'Wolo',
    'Yari',
  ],
  'Bembereke': [
    'Baoura',
    'Bembereke',
    'Bembereke Peulh',
    'Bembereke-Est',
    'Bembereke-Ouest',
    'Bereke-Gando',
    'Bereke-Gourou',
    'Berou',
    'Beroubouay',
    'Beroubouay Peulh',
    'Beroubouay-Est',
    'Beroubouay-Ouest',
    'Boke',
    'Boro',
    'Bouanri',
    'Bouanri-Gourou',
    'Bouanri-Maro',
    'Bouanri-Songoura',
    'Bouay',
    'Bouratebe',
    'Bouri',
    'Dantcha',
    'Gamare',
    'Gamia',
    'Gamia-Est',
    'Gamia-Ouest',
    'Gando',
    'Gando-Borou',
    'Ganro',
    'Gberou-Daba',
    'Goua',
    'Guera-N\'kali',
    'Guera-N\'kali-Tassi',
    'Guere',
    'Guessou-Banm Taka',
    'Guessou-Banm Taka-Ouest',
    'Guessou-Banm Taka-Peulh',
    'Guessou-Nord',
    'Ina',
    'Ina-Est',
    'Ina-Gando',
    'Ina-Ouest',
    'Ina-Peulh',
    'Kabanou',
    'Kassarou',
    'Kassarou Gnel Babi',
    'Kenekou',
    'Keroukpogo',
    'Kokabo',
    'Kongou',
    'Kongou-Peulh',
    'Konou',
    'Kossou',
    'Kpebera',
    'Mani-Boke',
    'Pedarou',
    'Saore',
    'Sikouro',
    'Sissigourou',
    'Sombouan',
    'Sombouan-Paris',
    'Teme',
    'Timboure',
    'Wanrarou',
    'Wodora',
    'Wonka-Gourou',
  ],
  'Bohicon': [
    'Adagame-Lisezoun',
    'Adame',
    'Adame-Adato',
    'Adame-Ahito',
    'Adanminakougon',
    'Agbadjagon',
    'Agbangon',
    'Agbanweme',
    'Agbokou',
    'Agongointo',
    'Agonvezoun',
    'Ahouadanou',
    'Ahouali',
    'Ahouame',
    'Ahouame-Ahito',
    'Aiweme',
    'Aligoudo',
    'Alikpa',
    'Atchonme',
    'Attogouin',
    'Avogbanna',
    'Bohicon I',
    'Bohicon Ii',
    'Dakpa',
    'Djessouhogon',
    'Djognangbo',
    'Djonouta',
    'Dokon',
    'Edjegbinmegon',
    'Fleli',
    'Gancon-Ponsa',
    'Gbanhicon',
    'Gbeto',
    'Gnidjazoun',
    'Helou',
    'Hezonho',
    'Honmeho',
    'Houndon',
    'Houndonho',
    'Kodota',
    'Kpatalocoli',
    'Kpocon',
    'Lissezoun',
    'Lokodave',
    'Lokozoun',
    'Lotcho',
    'Madje',
    'Manaboe',
    'Masse-Gbame',
    'Ouassaho',
    'Passagon',
    'Saclo',
    'Saclo-Alikpa',
    'Saclo-Sokon',
    'Sehoueho Houndonho',
    'Seme',
    'Siliho',
    'Sodohome',
    'Sodohome Centre',
    'Sogba',
    'Sokpadelli',
    'Todo',
    'Tovigome',
    'Vehou',
    'Volli',
    'Wangnassa',
    'Zakanme',
    'Zakpo-Adagame',
    'Zoungoudo',
    'Zounkpa-Agbotogon',
    'Zounzonme',
    'Zounzonsa',
  ],
  'Bonou': [
    'Abeokouta',
    'Adido',
    'Affame',
    'Affame-Centre',
    'Agbomahan',
    'Agbonan',
    'Agbosso',
    'Agbosso-Kota',
    'Agonhoui',
    'Agonkon',
    'Ahouanzonme',
    'Allankpon',
    'Assrossa',
    'Atchabita',
    'Atchonsa',
    'Atchonsa-Centre',
    'Attankpe',
    'Avlankanme',
    'Ayogo',
    'Azongbossa',
    'Azonzounme',
    'Bonou',
    'Bonou-Centre',
    'Dame-Wogon',
    'Dasso',
    'Dogba',
    'Dogba-He',
    'Gboa',
    'Gnanhoui Zounme',
    'Hounvigue',
    'Lokossa',
    'Ouebossou',
    'Sota',
    'Sotinkanme',
    'Tovoh',
    'Wovime',
    'Zomai',
  ],
  'Bopa': [
    'Adjame',
    'Agbodji',
    'Agboh',
    'Agongoh',
    'Agonsa',
    'Ahloume',
    'Akokponawa',
    'Akplenou',
    'Atoe',
    'Atohoue',
    'Aveganme',
    'Badazouin',
    'Bolime',
    'Bopa',
    'Dado',
    'Dakpla',
    'Dansatingo',
    'Devedji',
    'Dhodho',
    'Djadji',
    'Djekian',
    'Djidjozoun',
    'Djofloun',
    'Doguia',
    'Fandihouin',
    'Foncome',
    'Gantitomey',
    'Gbakpodji',
    'Gbedecome',
    'Gbedji-Come',
    'Gbetocome',
    'Gbozehoue',
    'Gnidonou',
    'Hangnanme',
    'Hegoh',
    'Hinkpeme',
    'Hombete',
    'Honhoui',
    'Hontokpome',
    'Houanguia',
    'Houeganmey',
    'Houegbo',
    'Houngoh',
    'Houngueme',
    'Hounve',
    'Hounviatouin',
    'Koweho',
    'Kpave',
    'Kpindjicome',
    'Kpindjigbedji',
    'Kplatoe',
    'Kpodin',
    'Kpota',
    'Lobogo',
    'Logloe',
    'Lonfin',
    'Masse',
    'Medessedji',
    'Medetogbo',
    'Missiafo',
    'Ouassa-Kpodji',
    'Ouocome',
    'Oussa Tokpa',
    'Ovoun',
    'Ozouedjame',
    'Possotome',
    'Sehomi-Datoh',
    'Sehomi-Kogbome',
    'Sehougbato',
    'Sinkpe-Gbolossouhoue',
    'Tanve',
    'Tchanhoue-Come',
    'Tchantchankpo',
    'Tekozouin',
    'Tohonou',
    'Tohoueta',
    'Tohoueta Akloh',
    'Tokpoe',
    'Towenou',
    'Yegodoe',
    'Yetoe',
    'Zinwegoh',
    'Zizague',
    'Zoungbo',
    'Zoungbo-Mission',
  ],
  'Boukoumbe': [
    'Agbonte',
    'Boukoumbe',
    'Didompe',
    'Dikon Hein',
    'Dikouani',
    'Dikoumini',
    'Dikouteni',
    'Dimansouri',
    'Dimatadonie',
    'Dimateco',
    'Dimatima',
    'Dipintakouani',
    'Dipokor',
    'Dipokor-Tchaaba',
    'Dipokorfontri',
    'Dipoli',
    'Dissapoli',
    'Ditchendia',
    'Ikounga',
    'Katchagniga',
    'Keyordake',
    'Korontiere',
    'Kototougou',
    'Koubegou',
    'Koubentiegou',
    'Koucogou',
    'Koucongou',
    'Koudadagou',
    'Koudahongou',
    'Koudogou',
    'Kougnangou',
    'Kouhemgou',
    'Koukoua',
    'Koukouakamangou',
    'Koukouangou',
    'Koukouangou-Boukoumbe',
    'Koukouankpangou',
    'Koukouatchiengou',
    'Koukouatougou',
    'Koukpetihagou',
    'Koukpintiegou',
    'Koumaagou',
    'Koumatie',
    'Koumontchirgou',
    'Kounadogou',
    'Kounagnigou',
    'Kounakogou',
    'Kounatchatiegou',
    'Kountchougou',
    'Koupagou',
    'Koupagou-Korontiere',
    'Kouporgou',
    'Koussakou',
    'Koussayagou',
    'Koussetiegou',
    'Koussocoingou',
    'Koussoucoingou',
    'Koussounongou',
    'Koutagou',
    'Koutangou',
    'Koutatiegou',
    'Koutayagou',
    'Koutcha-Koumagou',
    'Koutchantie',
    'Koutchata',
    'Koutchatahongou',
    'Koutchatie',
    'Koutoutongou',
    'Kouwatakouangou',
    'Kouwonatougou',
    'Kouwotchirgou',
    'Kouya',
    'Kperinkpe',
    'Manta',
    'Mantchari',
    'Nata',
    'Natchente',
    'Natieni',
    'Okouaro',
    'Otanongou',
    'Oukounserihoun',
    'Tabota',
    'Tadowonta',
    'Takotchienta',
    'Takotieta',
    'Takpanta',
    'Tassayota',
    'Tatchadieta',
    'Tatouta',
    'Tchapeta',
    'Tipaoti',
    'Yatie',
    'Zongo',
  ],
  'Cobly': [
    'Bagapodi',
    'Cobly',
    'Datori',
    'Gnangou',
    'Kadieni',
    'Kanadeke',
    'Kolgou',
    'Koukontouga',
    'Kountori',
    'Kpetienou',
    'Kpetissohoun',
    'Matale',
    'Nagnande',
    'Namatienou',
    'Namoutchaga',
    'Nanagade',
    'Nouangou',
    'Oroukouare',
    'Oukodoo',
    'Oukpetouhoun',
    'Oukpintihoun',
    'Ouorou',
    'Outanonhoun',
    'Ouyerihoun',
    'Pentinga',
    'Serhoungue',
    'Sienou',
    'Sinni',
    'Tapoga',
    'Tarpingou',
    'Tchamonga',
    'Tchokita',
    'Tokibi',
    'Touga',
    'Yimpissiri',
    'Zanniouri',
  ],
  'Come': [
    'Aclome',
    'Agatogbo',
    'Agblotome',
    'Agoutome',
    'Ahouandjigo Codji',
    'Akodeha',
    'Apehvedji',
    'Avedji',
    'Azannou',
    'Bowe-Gbedji',
    'Cocoucodji',
    'Come',
    'Degoue',
    'Deux Kilos',
    'Djacote',
    'Dohi',
    'Gadome',
    'Gative',
    'Gbedevinou',
    'Gboguinhoue',
    'Gonguegbo',
    'Gonguekpe',
    'Guezin Ahouandjigo',
    'Guezin Donhuinou',
    'Guezin Gbadou',
    'Guezin Zinkpanou',
    'Hongode',
    'Honnougbo',
    'Honve-Come',
    'Hotel De Ville',
    'Kande',
    'Kpetekan',
    'Kpetou',
    'Kpetou-Gahoue',
    'Kpodji',
    'Kpongonou',
    'Maison Des Jeunes',
    'Medemahoue',
    'Mezintome',
    'Mon Berger',
    'Mongnonhoui',
    'Nongo',
    'Ouedeme-Pedah',
    'Oumako',
    'Pedacome',
    'Sivame',
    'Sossigbe',
    'Soukpotome',
    'Tokan',
    'Tossouhon',
    'Totchon-Agni',
    'Tove',
    'Zounta',
  ],
  'Copargo': [
    'Anandana',
    'Babanzaoure',
    'Bamisso',
    'Bissinra',
    'Bom-Bom',
    'Boro-Kouri',
    'Cana',
    'Copargo',
    'Dakpera',
    'Dalkpalahou',
    'Djessekou',
    'Foungou',
    'Galora-Yabaga',
    'Gnanfounoum',
    'Gossina',
    'Kankoulga',
    'Karhum-Dora',
    'Karhum-Malero',
    'Karhum-Yaourou',
    'Katabam',
    'Koubenebene',
    'Koubokoubore',
    'Koukoulbendi',
    'Koutchanti',
    'Lefendi',
    'Maho',
    'N\'dam',
    'Nimourou',
    'Pabegou',
    'Palampagou',
    'Pargoute',
    'Passabia',
    'Passangre',
    'Satieka-Gbamdi',
    'Sema',
    'Setrah',
    'Singre',
    'Taho',
    'Tani',
    'Tchaklero',
    'Tchaklero Yarou',
    'Tchoutchou',
    'Tigninoun',
    'Wadherou',
    'Yaka',
    'Yaoura',
  ],
  'Cotonou': [
    '10eme Arrondissement',
    '11eme Arrondissement',
    '12eme Arrondissement',
    '13eme Arrondissement',
    '1er Arrondissement',
    '2eme Arrondissement',
    '3eme Arrondissement',
    '4eme Arrondissement',
    '5eme Arrondissement',
    '6eme Arrondissement',
    '7eme Arrondissement',
    '8eme Arrondissement',
    '9eme Arrondissement',
    'Abokicodji Centre',
    'Abokicodji Lagune',
    'Adjegounle',
    'Adogleta',
    'Agbato',
    'Agbodjedo',
    'Agbodjedo Ste Rita',
    'Agla Agongbomey',
    'Agla Akplomey',
    'Agla Figaro',
    'Agla Les Pylones',
    'Agla Petit Chateau',
    'Agla Sud',
    'Aglafinafa',
    'Agontinkon',
    'Agounvocodji',
    'Ahogbohoue Cite De L\'experience',
    'Ahogbohoue Cite Eucaristie',
    'Ahouanleko',
    'Ahouansori Agata',
    'Ahouansori Ague',
    'Ahouansori Ladji',
    'Ahouansori Toweta',
    'Ahouansori Toweta Kpotai',
    'Ahouassa',
    'Aibatin Dodo',
    'Aibatin Kpota',
    'Aidjedo',
    'Aidjedo Ahito',
    'Aidjedo Gbego',
    'Aidjedo Vignon',
    'Akogbato',
    'Akpakpa Dodome',
    'Avlekete Jonquet',
    'Avotrou Aimonlonfide',
    'Avotrou Gbego',
    'Avotrou Houezekome',
    'Ayelawadje',
    'Ayelawadje Agongome',
    'Bocossi Tokpa',
    'Cadjehoun Agonga',
    'Cadjehoun Aupiais',
    'Cadjehoun Azalokogon',
    'Cadjehoun Detinsa',
    'Cadjehoun Gare',
    'Cadjehoun Kpota',
    'Cite Adjaha',
    'Dagbedji Sike',
    'Dandji',
    'Dandji Hokanme',
    'Dantokpa',
    'Dedokpo',
    'Djedje-Laye',
    'Djidje',
    'Djidje Aichedji',
    'Donaten',
    'Dota',
    'Enagnon',
    'Enagnon-Sike',
    'Fidjrosse Centre',
    'Fidjrosse Kpota',
    'Fifadji',
    'Fifadji Houto',
    'Fifatin',
    'Fignon Sike',
    'Finagnon',
    'Fiyegnon Houta',
    'Fiyegnon Jacquot',
    'Gankpodo',
    'Gbedagba',
    'Gbedegbe',
    'Gbediga Guedehoungue',
    'Gbedjewin',
    'Gbedjromede',
    'Gbedjromede Sud',
    'Gbedokpo',
    'Gbedomidji',
    'Gbegamey Ahito',
    'Gbegamey Centre',
    'Gbegamey Dodo Ayidje',
    'Gbegamey Gbagoudo',
    'Gbegamey Mifongou',
    'Gbenan',
    'Gbenonkpo',
    'Gbeto',
    'Gbewa',
    'Gbodjetin',
    'Guinkomey',
    'Haie Vive',
    'Hinde Nord',
    'Hinde Sud',
    'Hlacomey',
    'Hlazounto',
    'Houehoun',
    'Houenoussou',
    'Houenoussou Ste Rita',
    'Houeyiho',
    'Houeyiho Tanou',
    'Irede',
    'Jericho Nord',
    'Jericho Sud',
    'Kindonou',
    'Kouhounou',
    'Kowegbo',
    'Kpankpan',
    'Kpondehou',
    'Kpondehou Tchemei',
    'Les Cocotiers',
    'Lom-Nava',
    'Mededjro',
    'Menontin',
    'Midedji',
    'Midombo',
    'Mifongou',
    'Minonkpo Wologuede',
    'Minontchou',
    'Missebo',
    'Missekple',
    'Missessin',
    'Missite',
    'Missite-Sike',
    'Missogbe',
    'N\'venamede',
    'Nouveau Pont',
    'Ohe',
    'Saint Jean Gbediga',
    'Sedami',
    'Sedjro Saint Michel',
    'Segbeya Nord',
    'Segbeya Sud',
    'Sehogan Sike',
    'Senade Sekou',
    'Senande',
    'Setovi',
    'Sodjeatinme Centre',
    'Sodjeatinme Est',
    'Sodjeatinme Ouest',
    'Suru Lere',
    'Tanto',
    'Tchanhounkpame',
    'Todote',
    'Tokpa Hoho',
    'Tokplegbe',
    'Tonato',
    'Vedoko',
    'Vodje Allobatin',
    'Vodje Ayidote',
    'Vodje Centre',
    'Vodje Finagnon',
    'Vodje Kpota',
    'Vossa',
    'Vossa-Kpodji',
    'Xwlacodji Kpodji',
    'Xwlacodji Plage',
    'Yagbe',
    'Yemicodji',
    'Yenawa',
    'Yenawa Daho',
    'Yenawa-Fifadji',
    'Yevedo',
    'Zogbo',
    'Zogbohoue',
    'Zongo Ehuzu',
    'Zongo Nima',
  ],
  'Cove': [
    'Abayahoue',
    'Adja',
    'Adogbe',
    'Aga',
    'Agbangnanhoue',
    'Agnangan',
    'Agossouhoue',
    'Ahito',
    'Aizondo',
    'Akpatchihoue',
    'Attogon',
    'Azehounholi',
    'Azonholi',
    'Bagon',
    'Dahoue',
    'Dahouigon',
    'Dangbehonou',
    'Dekpada',
    'Dome',
    'Finangnon',
    'Fonli',
    'Gandahogon',
    'Gounli',
    'Houeko',
    'Houeton',
    'Houeyiho',
    'Houin-Hounso',
    'Houndo',
    'Hounholi',
    'Hounvigueli',
    'Kpagoudo',
    'Lainta-Cogbe',
    'Makpegon',
    'Naogon',
    'Sekon-Djakpa',
    'Seslame',
    'Soli',
    'Toue',
    'Veme',
    'Voli',
    'Yenawa',
    'Zogba',
    'Zogoli',
    'Zoungoudo',
    'Zounsego',
  ],
  'Dangbo': [
    'Adjido',
    'Affio',
    'Agbanta',
    'Agbonou',
    'Agondo',
    'Agongue',
    'Akokponawa',
    'Akpame',
    'Akpame Vevi',
    'Aligbo',
    'Allanwadan',
    'Dame',
    'Dangbo',
    'Dangbo Honme',
    'Danko',
    'Dekin',
    'Deweme-Daho',
    'Djigbe',
    'Djigbe Houngon',
    'Dogla',
    'Dokome',
    'Fingninkanme',
    'Gbeko',
    'Gbeko Centre',
    'Gbeko Dekangbo',
    'Gbeko Sioli',
    'Gbessoume',
    'Glahounsa',
    'Glahounsa Seme',
    'Hetin-Glehoue',
    'Hetin-Sota',
    'Hondji',
    'Houedomey',
    'Hounhoue',
    'Hozin',
    'Ke',
    'Kessounou',
    'Kodekpeme',
    'Kodonou',
    'Lake',
    'Mitro',
    'Monnotokpa',
    'Seho Djigbe',
    'Sodji',
    'Togbohounsou',
    'Tokpa-Koudjota',
    'Tove',
    'Wozounmey',
    'Yokon',
    'Zoungue',
    'Zoungue Sai Lagare',
    'Zounta',
  ],
  'Dassa-Zoume': [
    'Adihinlidji',
    'Adjale',
    'Adjokan',
    'Agao',
    'Agbagoule',
    'Agbegbe',
    'Agbogbome',
    'Agbondjedo',
    'Agnanme',
    'Agondokpo',
    'Akoba',
    'Akoffodjoule',
    'Akpari-Arobassa',
    'Amangassa',
    'Arigbokoto',
    'Assiyo',
    'Atake',
    'Attinkpaye',
    'Awaya',
    'Ayedero',
    'Ayetou',
    'Bakema',
    'Banigbe',
    'Betecoucou',
    'Betou',
    'Dassa I',
    'Dassa Ii',
    'Djigbe',
    'Dogbo',
    'Dome',
    'Dovi-Some',
    'Erokowari',
    'Erokoya',
    'Essebre',
    'Essekpa',
    'Essekpre',
    'Fita',
    'Gankpetin',
    'Gbaffo',
    'Gbedavo',
    'Gbonou',
    'Gbowele',
    'Gnonkpingnon',
    'Godogossou',
    'Goussoe',
    'Hasseou',
    'Holli-Gamba-Itchedoun',
    'Hounkpogon',
    'Idaho',
    'Igoho',
    'Iloule',
    'Issalou',
    'Itagui',
    'Itchegou',
    'Itchogue-Sotre',
    'Kere',
    'Kindji',
    'Kpakpa',
    'Kpakpada-Agbakossare',
    'Kpekoute',
    'Kpekpede',
    'Kpingni',
    'Lamanou',
    'Latin',
    'Lema',
    'Lissa',
    'Lokossa',
    'Lotogo',
    'Mahou',
    'Manonfi',
    'Miniffi',
    'Modji-Gangan',
    'Moudja',
    'Moumoudji',
    'N\'gbega',
    'Odo-Otchere',
    'Okemere',
    'Oueme',
    'Ouissi',
    'Paouingnan',
    'Seme',
    'Soclogbo',
    'Sourhedji-Okpe Olouwa',
    'Sovogo',
    'Tangbe',
    'Tchamissi-Laguema-Atakeagbassa',
    'Tchaounka',
    'Tini-Kodjatchan',
    'Togon',
    'Tre',
    'Vedji',
    'Vidjinnatoun',
    'Yara',
    'Zongo',
    'Zotedji',
    'Zougoudo',
    'Zouto',
  ],
  'Djakotomey': [
    'Ablomey',
    'Adjintimey',
    'Agbedranfo',
    'Agohoue-Balimey',
    'Aissanhoue',
    'Aivohoue',
    'Akodebakou',
    'Ameganhoue',
    'Assogbahoue',
    'Atchouhoue',
    'Avodjihoue',
    'Avonnouhoue',
    'Babohoue',
    'Bahoue',
    'Beotchi',
    'Betoumey',
    'Betoumey Centre',
    'Bota',
    'Danmakahoue',
    'Danssouhoue',
    'Dassouhoue',
    'Demahouhoue',
    'Djakotomey Centre',
    'Djakotomey I',
    'Djakotomey Ii',
    'Djonouhoue',
    'Dogohoue',
    'Doumahou',
    'Dowomey',
    'Edjihoue',
    'Etonhoue',
    'Fannahinhoue',
    'Fantchoutchehoue',
    'Fogbadja Centre',
    'Game-Fode',
    'Game-Houegbo',
    'Gbekehoue',
    'Gbemahlouehoue',
    'Gbognonhoue',
    'Gbotohoue',
    'Gboyouhoue',
    'Godouhoue',
    'Gohomey',
    'Gohomey Centre',
    'Golamey',
    'Gomehouin',
    'Hagoumey Centre',
    'Hekpe',
    'Holou-Loko',
    'Houegamey',
    'Houngba',
    'Houngbedjihoue',
    'Houngbezanme',
    'Hounhomey',
    'Hounkemey',
    'Kansouhoue',
    'Kanvihoue',
    'Kessahouedji',
    'Kinkinhoue',
    'Kokohoue',
    'Kpatohoue',
    'Kpayahoue',
    'Kpeladjamey',
    'Kpoba',
    'Loko-Atoui',
    'Lokoui-Bedjamey',
    'Mahinouhoue',
    'Mededjihoue',
    'Mekpohoue',
    'Migbowomey',
    'Mouzoukpokpohoue',
    'Nakidahohoue',
    'Nouboudji',
    'Sahou-Sohoue',
    'Sebiohoue-Adjintimey',
    'Segbehoue',
    'Seglahoue',
    'Semanouhoue',
    'Sogbavihoue',
    'Sokouhoue',
    'Tchanhoue',
    'Tedehoue',
    'Titongon',
    'Tohouehoue',
    'Tokpohoue',
    'Wanou',
    'Zohoudji',
    'Zouzouvou',
  ],
  'Djidja': [
    'Adame',
    'Adame-Houeglo',
    'Agblokpa',
    'Agbohoutogon',
    'Agondji',
    'Agondokpoe',
    'Agonhohoun',
    'Agouna',
    'Ahito',
    'Ahokanme',
    'Ahozoun',
    'Aihouidji',
    'Aklinme',
    'Amakpa',
    'Amontika',
    'Assan',
    'Assantoun',
    'Avokanzoun',
    'Awotrele',
    'Ayogbe',
    'Betta',
    'Bohoue',
    'Bookou',
    'Chie',
    'Daanon-Kpota',
    'Dan',
    'Danmlonkou',
    'Denou',
    'Djessi',
    'Djidja Centre',
    'Djidja-Aligoudo',
    'Djoho',
    'Djrekpedji',
    'Dohouime',
    'Dona',
    'Dridji',
    'Fonkpame',
    'Fonkpodji',
    'Gangan',
    'Gbadagba',
    'Gbihoungon',
    'Gobaix',
    'Gounoukouin',
    'Goutchon',
    'Hanagbo',
    'Hevi',
    'Honhoun',
    'Houkpa',
    'Hounvi',
    'Houto',
    'Kassehlo',
    'Katakenon (kaka Tehou)',
    'Kingbe',
    'Kohougon',
    'Kokoroko',
    'Kome',
    'Koudagba',
    'Kouekouekanme',
    'Kougbadji',
    'Kpakpanene',
    'Kpeteta',
    'Lagbado',
    'Lakpo',
    'Lalo',
    'Lele-Adato',
    'Linsinlin',
    'Lobeta',
    'Lotcho-Ahouame',
    'Lotcho-Daho',
    'Madjavi',
    'Magassa',
    'Monsourou',
    'Mougnon',
    'Mougnon-Ake',
    'Mougnon-Kossou',
    'Nontchedigbe',
    'Oumbegame',
    'Saloudji',
    'Sankpiti',
    'Savakon',
    'Sawlakpa',
    'Setto',
    'Sovlegni',
    'Sozoun',
    'Tannouho',
    'Tokegon',
    'Tokounkoun',
    'Tokpe',
    'Tossota',
    'Vevi',
    'Wogbaye',
    'Wokou',
    'Yagbanougon',
    'Ye',
    'Zadakon',
    'Zakan',
    'Zinkanme',
    'Zoungahou',
    'Zounkon',
    'Zounme',
  ],
  'Djougou': [
    'Abintaga',
    'Afatalanga',
    'Agorogossi',
    'Akekerou',
    'Alfa Kpara',
    'Alfa-Issa',
    'Angara',
    'Angaradebou',
    'Angba',
    'Anoum',
    'Bakou',
    'Bandessar',
    'Bandetchohi',
    'Baparape',
    'Barei',
    'Barei Vaaha',
    'Barei-Saoupehoun',
    'Bari',
    'Barienou',
    'Bassala',
    'Batoulou',
    'Batoulou Mounla',
    'Bellefoungou',
    'Bonborh',
    'Bortoko',
    'Bougou',
    'Bougou Fana',
    'Bougou Lira',
    'Bouloum',
    'Boumvari',
    'Boungourou',
    'Dabogou',
    'Dangoussar',
    'Danogou',
    'Daringa',
    'Dedera',
    'Demsihou',
    'Dendougou',
    'Dewa',
    'Djakpingou',
    'Djougou I',
    'Djougou Ii',
    'Djougou Iii',
    'Donga',
    'Donwari',
    'Formagazi',
    'Foumbea',
    'Founga',
    'Foyo',
    'Gah',
    'Gangamou',
    'Gaouga',
    'Gbessou',
    'Gnansonga',
    'Gnogambi',
    'Gnonri',
    'Gogoniga',
    'Gondessar',
    'Gorobani',
    'Gosso',
    'Goumbakou',
    'Issamanga',
    'Kakabounou-Beri',
    'Kakindoni',
    'Kamouhou',
    'Kilir',
    'Koha',
    'Kokossika',
    'Koloconde',
    'Koloconde Zongo',
    'Kolokonde Saoupehoun',
    'Korokou',
    'Koua',
    'Kourli',
    'Kpali',
    'Kpamalangou',
    'Kpandouga',
    'Kpaouya',
    'Kparsi',
    'Kpatouhou',
    'Kpayeroun',
    'Kpebouco',
    'Kpegounou',
    'Leman-Bogou',
    'Leman-Mande',
    'Madina',
    'Minanga',
    'Momongou',
    'Mone',
    'Morwatchohi',
    'Nagatchohi',
    'Nalohou',
    'Nanogou',
    'Noumane',
    'Onklou',
    'Onklou Pahanoun',
    'Onklou Saoupehoun',
    'Paparanga',
    'Partago',
    'Pelebina',
    'Petoni-Poho-Gorobani',
    'Petoni-Poho-Partago',
    'Potokou',
    'Sapaha',
    'Sassirou',
    'Sehvessi',
    'Selra',
    'Selrou',
    'Serou',
    'Sinassingou',
    'Sosso',
    'Soubroukou',
    'Taifa',
    'Tamohoun',
    'Tebou',
    'Tepredjissi',
    'Tewaou',
    'Timtim-Bongo',
    'Toko-Toko',
    'Tolra',
    'Vanhoui',
    'Wargou',
    'Wassa',
    'Wewe',
    'Yarakeou',
    'Yorossonga',
    'Zembougou-Beri',
    'Zongo',
    'Zountori',
  ],
  'Dogbo': [
    'Achitou',
    'Adandro-Akode',
    'Adidevo',
    'Agbedranfo',
    'Agbegnidohoue',
    'Agnavo',
    'Ahomey',
    'Allada',
    'Atchanhoue',
    'Avedjin',
    'Avegode',
    'Ayesso',
    'Ayomi',
    'Ayomi Centre',
    'Botagbe',
    'Codjohoue',
    'Dadohoue',
    'Dahoue',
    'Deguihoue',
    'Dekandji',
    'Deve',
    'Deve-Homey',
    'Fafadji',
    'Fambohoue',
    'Foncome Agandannonhoue',
    'Foncome Agbohoue',
    'Foncome Gouhoun',
    'Foncome Tetehoue',
    'Gbakehoue',
    'Gbannave',
    'Gnigbe',
    'Godohou',
    'Hedjame',
    'Honton',
    'Houedjamey',
    'Houndrome',
    'Houngloui',
    'Hounsa',
    'Kegbehoue',
    'Kenavo',
    'Kenouhoue',
    'Ketchandji-Kpoledji',
    'Koutime',
    'Kpodaha Centre',
    'Kpodaha Deka',
    'Kpodave',
    'Kpodji',
    'Kpogodou',
    'Kpoha',
    'Lokogba',
    'Lokogohoue',
    'Madankanmey',
    'Madjre',
    'Madjre Centre',
    'Midangbe',
    'Segba',
    'Togannou',
    'Tokpota',
    'Tota',
    'Tota Balime',
    'Tota Kpodji',
    'Totchangni',
    'Totchangni Centre',
    'Toulehoudji',
    'Vehidji',
    'Zaphi Gnamamey',
    'Zaphi Houeganme',
    'Zaphi Hounsa',
    'Zohoudji',
    'Zokpedji',
  ],
  'Glazoue': [
    'Abessouhoue',
    'Adourekoman',
    'Affecia',
    'Affizoungo',
    'Affizoungo-Kpota',
    'Agbagbadji',
    'Agouagon',
    'Agouagon-Gnonnougbo',
    'Aidjesso',
    'Aklampa',
    'Akomyan',
    'Akouegba',
    'Allawenonsa',
    'Allawenonsa-Tchaha',
    'Amanhoungavissa',
    'Antadji',
    'Assante',
    'Assromihoue',
    'Ateguedji',
    'Atogbo',
    'Ayedero',
    'Bethel',
    'Boubou',
    'Camate',
    'Dehoudoho',
    'Djanmandji',
    'Dokoundji',
    'Egbessi',
    'Gbanlin',
    'Gbanlin-Fifadji',
    'Glazoue',
    'Gome',
    'Goto',
    'Hai',
    'Haya',
    'Hlassoe',
    'Hoco',
    'Houala',
    'Houin',
    'Houin-Segbeya',
    'Houndjro Kpogandji',
    'Ifada-Zoungue',
    'Kabole',
    'Kpakpaza',
    'Kpakpazounme',
    'Kpassali',
    'Kpota',
    'Lagbo',
    'Madengbe',
    'Magoumi',
    'Monso',
    'Ogoudako',
    'Oguirin',
    'Oke-Okounou',
    'Okeo',
    'Orokoto',
    'Ouedeme',
    'Ouedeme Centre',
    'Riffo',
    'Sokponta',
    'Sokponta Centre',
    'Sowe',
    'Sowe-Ikpakpada',
    'Sowiandji',
    'Tankossi',
    'Tchakaloke',
    'Tchatchegou',
    'Thio',
    'Yagbo',
    'Yawa',
    'Yemanlin',
    'Yevedo',
    'Zaffe',
    'Zaffe Centre',
    'Zongo',
  ],
  'Gogounou': [
    'Badou',
    'Bagou',
    'Bagou-Sinkparou',
    'Bagou-Yagbo',
    'Banigoure',
    'Bantansoue',
    'Bepororo',
    'Binga',
    'Boro',
    'Borodarou',
    'Bouyagourou',
    'Dagourou',
    'Dassari',
    'Diadia',
    'Diguisson',
    'Dimdimnou',
    'Djinmele',
    'Donwari',
    'Dougou',
    'Dougoulaye',
    'Fanan',
    'Gamagou',
    'Gando-Dari',
    'Gandobou',
    'Garagoro',
    'Gasso',
    'Gbemoussou',
    'Gbessa',
    'Gnindarou',
    'Gogounou',
    'Gogounou-Gbanin',
    'Gogounou-Nassabara',
    'Goubera',
    'Gounarou',
    'Goure Dantcha',
    'Kale',
    'Kali',
    'Kangnan',
    'Kantakpara-Wokparou',
    'Kantakpara-Wokperou',
    'Kassirou',
    'Kerou-Bagou',
    'Konsenin',
    'Kpakaguere',
    'Kpigourou',
    'Lafiarou',
    'Nafarou',
    'Orou-Bedou',
    'Ouere-Bani',
    'Ouere-Sonkerou',
    'Ouessene-Worou',
    'Pariki',
    'Petit-Paris',
    'Sonkorou',
    'Sori',
    'Sori-Boro Wanrou',
    'Sori-Kpankpanou',
    'Sori-Peulh',
    'Sorou',
    'Sougou-Gourou',
    'Sougou-Kpan-Trossi',
    'Sougou-Kpantrossi',
    'Soukarou',
    'Taiti',
    'Tawali',
    'Tchoupounga',
    'Wara',
    'Wara-Gah',
    'Wara-Gbidogo',
    'Yankpannou',
  ],
  'Grand-Popo': [
    'Adankpe',
    'Adimado',
    'Adjaha',
    'Adjigo',
    'Agonnekanmey',
    'Agoue',
    'Agoue Gbedjin',
    'Akodessewa',
    'Allongo',
    'Apoutagbo',
    'Avlo',
    'Avlo Houta',
    'Awame',
    'Ayiguinnou',
    'Bathoto',
    'Conho',
    'Cotocoli',
    'Devikanmey',
    'Djanglamey',
    'Djanglanmey',
    'Ewe Condji',
    'Folly Condji',
    'Gbeawa',
    'Gbedji',
    'Gbehoue',
    'Gbehoue Ouatchi',
    'Gbehoue Pedah',
    'Gninhountime',
    'Gnito',
    'Gountoeto',
    'Grand-Popo',
    'Hakoue',
    'Hanmlangni',
    'Heve',
    'Heyi Gbadji',
    'Hilla Condji',
    'Houndjohoundji',
    'Hounkounnou',
    'Hounsoukoe',
    'Koueta',
    'Kpable',
    'Kpatcha-Condji',
    'Kpeko',
    'Kpovidji',
    'Louis Condji',
    'Missihoun Condji',
    'Nicoue Condji',
    'Onkuihoue',
    'Saligato',
    'Sazue',
    'Seho Condji',
    'Sohon',
    'Tala',
    'Todjonoukoin',
    'Toklanhon',
    'Tokpa Monoto',
    'Tokpa-Aizo',
    'Tolebekpa',
    'Tomadjihoue',
    'Vodomey',
    'Yodo Condji',
    'Zogbedji',
  ],
  'Houeyogbe': [
    'Adjame',
    'Adjigo',
    'Adrome Gbeto',
    'Adrome Kpovidji',
    'Agle',
    'Agongoh',
    'Aguehon',
    'Ahouloume',
    'Akloh',
    'Allogo',
    'Dahe',
    'Dahe-Aklo',
    'Dahe-Gbedji',
    'Dahe-Kpodji',
    'Danhoue',
    'Danklo',
    'Dave',
    'Devedji',
    'Didongbogoh',
    'Dincome',
    'Djetoe',
    'Djibio',
    'Dodji',
    'Doutou',
    'Doutou-Akloh',
    'Doutou-Fifadji',
    'Doutou-Hehouin',
    'Doutou-Kpodji',
    'Dre',
    'Dre-Lonmnava',
    'Ekindji',
    'Gahoue',
    'Gahouin',
    'Gave',
    'Gbadagli',
    'Gbagbonou',
    'Gbahossouhoue',
    'Gbedji',
    'Gboho',
    'Gnamako',
    'Gnitonou',
    'Gogohondji',
    'Gonfiocomey-Nord',
    'Gonfiocomey-Sud',
    'Hecondji',
    'Hinde',
    'Hlassigounme',
    'Hlassigounme-Akloh',
    'Honhoue',
    'Honnougbo',
    'Houankpa',
    'Houankpato',
    'Houetihoue',
    'Houeyogbe',
    'Houingah-Houegbe',
    'Houingah-Salahoue',
    'Hounvi',
    'Hounvi Atchago',
    'Kedji',
    'Kowenou',
    'Kpansouingoh',
    'Kpassakanme',
    'Kpetou-Gbadji',
    'Kpodji',
    'Logohoue',
    'Lokohoue',
    'Maiboui',
    'Maiboui-Akloh',
    'Manonkpon',
    'N\'konouhoue',
    'Se',
    'Sebo',
    'Sewacomey',
    'Sohounme',
    'Togbonou',
    'Tohon',
    'Tohonou',
    'Tohouin',
    'Tokpa',
    'Vegodoe',
    'Zindjihoue',
    'Zoungbonou',
    'Zounme',
  ],
  'Ifangni': [
    'Adanmayi',
    'Agbodjedo',
    'Akadja',
    'Akadja-Agamadin',
    'Akadja-Gbodje',
    'Akadja-Goutedo',
    'Araromi',
    'Ayetedjou',
    'Banigbe',
    'Banigbe Gare',
    'Banigbe Lokossa',
    'Banigbe-Nagot',
    'Baodjo',
    'Daagbe',
    'Daagbe-Djedje',
    'Daagbe-Nagot',
    'Dan',
    'Dangban',
    'Dessah',
    'Djegou-Ayidjedo',
    'Djegou-Djedje',
    'Djegou-Nagot',
    'Dooke',
    'Dooke-Hanzoume',
    'Dooke-Sedje',
    'Ganmi',
    'Gblogblo',
    'Gblogblo Agbodjedo',
    'Gbokou',
    'Gbokoutou',
    'Hego',
    'Houmbo-Djedje',
    'Houmbo-Nagot',
    'Idi-Oro',
    'Ifangni',
    'Ifangni-Odofin',
    'Igolo',
    'Iguignanhoun',
    'Iko',
    'Ita-Elekpete',
    'Ita-Kpako',
    'Ita-Soumba',
    'Iyoko',
    'Ketou Gbecon',
    'Ketoukpe',
    'Kitigbo',
    'Ko-Agonkessa',
    'Ko-Anagodo',
    'Ko-Ayidjedo',
    'Ko-Dogba',
    'Ko-Gbegodo',
    'Ko-Houeze',
    'Ko-Koumolou',
    'Ko-Ogou',
    'Ko-Zoungodo',
    'Kouye',
    'Lagbe',
    'Loko-Koukou',
    'Lokossa-Alihogodo',
    'Loube',
    'Mongba',
    'Oke-Odja',
    'Okedjere',
    'Sedo',
    'Sobe',
    'Sobe-Ayelawadje',
    'Sokou',
    'Sokou-Alihogbogo',
    'Sori',
    'Tamondo',
    'Tchaada',
    'Tchaada Centre',
    'Zian',
  ],
  'Kalale': [
    'Ada-Kpane',
    'Alafiarou-Derassi',
    'Alafiarou-Gando',
    'Angaradebou',
    'Bagaria',
    'Banagbasson',
    'Banezi',
    'Banezi Peulh',
    'Basso',
    'Basso-Peulh',
    'Batin',
    'Bessassi',
    'Bessassi-Bea',
    'Bessassi-Bouca',
    'Bessassi-Gando',
    'Boa',
    'Boa-Gando',
    'Bouca',
    'Bouca-Gando',
    'Bouca-Peulh',
    'Bouca-Woorou',
    'Bouraoure',
    'Dadi',
    'Danganzi',
    'Dangorou',
    'Derassi',
    'Djega-Dunkassa',
    'Djega-Kalale',
    'Djilidjalare',
    'Dunkassa',
    'Dunkassa-Peulh',
    'Gando-Baka',
    'Gando-Gourou',
    'Gannoure-Here',
    'Gawezi',
    'Gbassi',
    'Gbassi-Gando',
    'Gbei',
    'Gbekona',
    'Gberougbassi',
    'Gbessakperou',
    'Gnel-Boucatou',
    'Gnel-Djobo',
    'Gnel-Gamadje',
    'Gnel-Kele',
    'Gnel-Yakan',
    'Gorobani',
    'Gorogawo',
    'Gossodji',
    'Goudema',
    'Guiri-Gando',
    'Guiri-Peulh',
    'Kaala',
    'Kakatinnin',
    'Kalale',
    'Kalale-Peulh',
    'Kalale-Sessouan',
    'Kalale-Zina',
    'Karel',
    'Kidaroukperou',
    'Kiricoube',
    'Korodji',
    'Kourel',
    'Ladouga',
    'Lou',
    'Mareguinta',
    'Matchore',
    'Nassiconzi',
    'Neganzi',
    'Neganzi-Peulh',
    'Ouenagourou',
    'Peonga',
    'Sebana',
    'Seregourou',
    'Toucare',
    'Wobadje',
    'Wonko',
    'Yolla',
    'Zambara',
  ],
  'Kandi': [
    'Akoitchaou',
    'Al Barika',
    'Alekpare',
    'Alfakoara',
    'Alibori-Yankin',
    'Angaradebou',
    'Bakpara',
    'Banigourou',
    'Banikani',
    'Baobab',
    'Bensekou',
    'Bikongou',
    'Boderou',
    'Boderou-Peulh',
    'Damadi',
    'Dinin',
    'Dinin Peulh',
    'Dodondawa Somoutere',
    'Dodopanin',
    'Dogban',
    'Donwari',
    'Donwari-Peulh',
    'Fafa',
    'Firi',
    'Fouet',
    'Foure',
    'Gambane',
    'Gambane-Peulh',
    'Gando',
    'Gando-Kossikana',
    'Gansosso-Gbiga',
    'Gansosso-Yirousse',
    'Gbindarou',
    'Gbokoukou',
    'Gogbede',
    'Gogore',
    'Gourou Peulh',
    'Heboumey',
    'Kabagbede',
    'Kadjere',
    'Kandi 1',
    'Kandi 2',
    'Kandi 3',
    'Kandi-Fo',
    'Kandi-Fo-Peulh',
    'Kassakou',
    'Keferi-Hinkante',
    'Keferi-Sinte',
    'Kossarou',
    'Koutakroukou',
    'Kpalolo',
    'Kpessarou',
    'Lafiarou',
    'Lolo',
    'Madina',
    'Mongo',
    'Mongo-Peulh',
    'Pade',
    'Pade-Peulh',
    'Pede',
    'Pedigui',
    'Pegon',
    'Podo',
    'Saah',
    'Sakatoussa',
    'Sam',
    'Sam-Gokirou',
    'Sam-Peulh',
    'Sekale',
    'Siderou',
    'Sinawongourou',
    'Sinawongourou-Peulh',
    'Sinikoussou-Beri',
    'Sondo',
    'Sonsoro',
    'Sonsoro-Peulh',
    'Soundou',
    'Tankongou',
    'Tankongou-Dagourou',
    'Tchoka',
    'Teri',
    'Thuy',
    'Thya',
    'Tissarou',
    'Tissarou-Peulh',
    'Touko',
    'Wonga',
    'Zerman-Koure',
  ],
  'Karimama': [
    'Bako-Maka',
    'Banikani',
    'Banizoumbou',
    'Bello-Tounga',
    'Birni Lafia',
    'Bogo-Bogo',
    'Bongnami',
    'Dangazori',
    'Fadama',
    'Fakara',
    'Fandou',
    'Garbey-Koara',
    'Goroukambou',
    'Goumbitchigoura',
    'Goungou-Beri',
    'Gourou Beri',
    'Kangara-Peulh',
    'Karigui',
    'Karimama',
    'Karimama-Batouma-Beri',
    'Karimama-Dendi-Koure',
    'Kene-Tounga',
    'Koaratedji',
    'Kofounou',
    'Kompa',
    'Kompanti',
    'Loumbou-Loumbou',
    'Machayan-Marche',
    'Mamassy-Gourma',
    'Mamassy-Peulh',
    'Missira',
    'Monsey',
    'Petchinga',
    'Saboula',
    'Tondikoaria',
    'Tondoobon',
    'Torioh',
    'Toura',
  ],
  'Kerou': [
    'Bagoubagou',
    'Bakoussarou',
    'Bambaba',
    'Bassini',
    'Batenin',
    'Berekossou',
    'Bipotoko',
    'Boukoubourou',
    'Brignamaro',
    'Djoleni',
    'Fetekou',
    'Fetekou -Alaga',
    'Firou',
    'Gambore',
    'Gando Baka',
    'Gantodo',
    'Gnampoli',
    'Gnangnanou',
    'Gori',
    'Gorobani',
    'Gougninnou',
    'Kabongourou',
    'Kaobagou',
    'Karigourou',
    'Kedarou',
    'Kerou',
    'Kerou Wirou',
    'Kokokou',
    'Kongourou',
    'Kossou',
    'Kossou-Ouinra',
    'Kparategui',
    'Manou',
    'Ouore',
    'Pikire',
    'Pikire-Adaga',
    'Sinagourou',
    'Sokoungourou',
    'Tchoukagnin',
    'Toudakou Banyirou',
    'Warou N\'gourou',
    'Yakin-Motoko',
    'Yakrigorou',
    'Yinsiga',
    'Yiroubara',
  ],
  'Ketou': [
    'Adakplame',
    'Adjozounme',
    'Agonlin-Kpahou',
    'Agozounme',
    'Aguidi',
    'Aguigadji',
    'Akpakame',
    'Akpambaou',
    'Alagbe-Illikimoun',
    'Alakouta',
    'Assena',
    'Atan-Ochoukpa',
    'Atanka',
    'Atchoubi',
    'Awai',
    'Awaya',
    'Ayekotonian',
    'Ayekou',
    'Ayelawadje',
    'Ayetedjou',
    'Bolorounfe',
    'Dagbandji',
    'Dogo',
    'Edenou',
    'Effeoute',
    'Emeda-Igboiloukan',
    'Ewe',
    'Gangnigon',
    'Gbaka-Nanze',
    'Gbegon',
    'Idadje',
    'Idena',
    'Idigny',
    'Idjabo',
    'Idjedje',
    'Idjou',
    'Idoufin',
    'Igbo-Ede',
    'Igbo-Igannan',
    'Igboola-Ofiri',
    'Igui-Olou',
    'Ikoko',
    'Illadji',
    'Illara-Kanga',
    'Illechin',
    'Illikimoun',
    'Illikimoun-Kolly',
    'Imonle-Ayo',
    'Inanse',
    'Iradigban',
    'Isselou',
    'Iwessoun',
    'Iwoye-Benin',
    'Kajola',
    'Ketou',
    'Kewi',
    'Kinwo',
    'Kozounvi',
    'Kpankou',
    'Massafe',
    'Mowodani',
    'Obafemi',
    'Obatedo',
    'Odi-Aro',
    'Odokoto',
    'Odometa',
    'Ofia',
    'Oguelete',
    'Oguidigbo',
    'Ohizihan',
    'Oke-Ola',
    'Okpometa',
    'Oloka',
    'Olorounshogo',
    'Omou',
    'Ossokodjo',
    'Sodji',
    'Vedji',
    'Woroko',
    'Zounkpe-Etigbo',
  ],
  'Klouekanmey': [
    'Adahoue',
    'Adjahonme',
    'Agbago',
    'Agblecome',
    'Agbodonhouin',
    'Aglali',
    'Ahogbeya',
    'Ahoudji',
    'Akime',
    'Akouegbadja',
    'Avegandji',
    'Aveganme',
    'Ayahohoue',
    'Betoume',
    'Dadji',
    'Dangnonchihoue',
    'Davihoue',
    'Davitohoue',
    'Dayehoue',
    'Dekandji',
    'Djidjoli',
    'Djihami',
    'Djotto',
    'Edahoue',
    'Ehuzu',
    'Fidegnonhoue',
    'Gahayadji',
    'Gahayanou',
    'Gbeblehoue',
    'Gbehounkochihoue',
    'Gbowime',
    'Glolihoue',
    'Gnantchime',
    'Gnigbou',
    'Gnigbougan',
    'Godohou',
    'Golouhoue',
    'Hohluime',
    'Hondjin',
    'Hondjin Centre',
    'Hondjingan',
    'Honhlonmitonhou',
    'Houenoussou',
    'Kedji',
    'Klossou',
    'Klouekanme',
    'Klouekanme - Gare',
    'Kogbetohoue',
    'Kome',
    'Kpakpassa',
    'Kpevidji',
    'Kplakatagon',
    'Lanta',
    'Lanta Centre',
    'Mademe',
    'Nanome',
    'Olouhoue',
    'Sawame-Hossouhoue',
    'Sawame-Houeyiho',
    'Seglahoue',
    'Soglonouhoue',
    'Sokpame',
    'Tangbanvime',
    'Tchanhouiwanwoui',
    'Tchanvedji',
    'Tcheton',
    'Tchikpe',
    'Tchokpohoue',
    'Toime',
    'Tokanme-Kpodji',
    'Tokanme-Montou',
    'Totroyoyou',
    'Yenawa',
    'Yevihoue',
    'Zohoudji',
    'Zondrebohoue',
    'Zouvou',
    'Zouzoukanme',
  ],
  'Kouande': [
    'Bassilou',
    'Becket-Bourame',
    'Becket-Peulh',
    'Birni',
    'Birni Maro',
    'Birni-Kankoulka',
    'Birni-Kpebirou',
    'Bore',
    'Boro',
    'Boroukou-Peulh',
    'Boroyinde',
    'Chabi Couma',
    'Chabi-Couma',
    'Damouti',
    'Danri',
    'Darou-Wirou',
    'Dekerou',
    'Foo',
    'Foo-Mama',
    'Foo-Tance',
    'Ganikperou',
    'Gantieco',
    'Gbeniki',
    'Gora-Peulh',
    'Gorgoba',
    'Goufanrou',
    'Goutere',
    'Guilmaro',
    'Guilmaro-Bounkossorou',
    'Guilmaro-Garkousson',
    'Guilmaro-Sinakpagourou',
    'Hongon',
    'Kabare',
    'Kedekou',
    'Ketere',
    'Kouande',
    'Kouboro',
    'Kpakou-Tankonga',
    'Kpankpankou',
    'Kpessinin',
    'Kpessourou',
    'Kpikire Koka',
    'Maka',
    'Makrou-Gourou',
    'Maro',
    'Mary',
    'Nassoukou',
    'Niarissinra',
    'Niaro-Gninon',
    'Niarosson',
    'Niekene-Bansou',
    'Orouboussoukou',
    'Orougbeni',
    'Oroukayo',
    'Ouroufina',
    'Papatia',
    'Pelima',
    'Poupoure',
    'Sakabou',
    'Sakasson-Ditamari',
    'Sakasson-Dompago',
    'Sekogourou',
    'Sekogourou-Baila',
    'Seri',
    'Sinakpaworou',
    'Somboko',
    'Sonnougoberou',
    'Sowa',
    'Tamande',
    'Tance',
    'Tassigourou',
    'Tikou',
    'Tokoro',
    'Weme',
    'Yakabissi',
    'Yinkene',
    'Zongo',
  ],
  'Kpomasse': [
    'Adjaglo',
    'Adjame',
    'Adjatokpa',
    'Aganmalome',
    'Aganmalome-Centre',
    'Agbanto',
    'Agbanto-Maga',
    'Agbanto-Sotoncodji',
    'Agbanto-Zounmin',
    'Agonkanme',
    'Agonkanme Centre',
    'Agonvodji-Daho',
    'Agonvodji-Kpevi',
    'Ahouango Agbidicome',
    'Ahouango Hinsocome',
    'Aidjedo',
    'Amoukonou',
    'Assogbenou-Daho',
    'Assogbenou-Kpevi',
    'Atchakanme',
    'Azizonkanme',
    'Cocoundji',
    'Couffonou',
    'Danzounme',
    'Dedome',
    'Dedome Aclome',
    'Dedome Kpodji',
    'Dekanme',
    'Doga',
    'Fifadji',
    'Foncome',
    'Ganganhouli',
    'Gbedjewin Adjibamey',
    'Gbefadji',
    'Gbefadji-Aidjedo',
    'Gbetozo',
    'Gboho',
    'Glegbotonou',
    'Godonoutin',
    'Gogotinkponme',
    'Gome',
    'Guezohoue',
    'Hessa',
    'Hinmadou',
    'Hinzoume',
    'Houedjro',
    'Houegan',
    'Houeton',
    'Houeyogbe',
    'Houngbogba',
    'Kougbedji',
    'Kouzoume',
    'Kpago',
    'Kpindjakanme',
    'Kpodji Atingo',
    'Kpodji Clotome',
    'Kpomasse Centre',
    'Kpota',
    'Lokogbo Gnonwa',
    'Lokogbo Zounta',
    'Lokossa',
    'Missebo',
    'Missite',
    'Nazoume',
    'Nonvignon',
    'Nougboyifi',
    'Ountoun',
    'Oussa',
    'Sebo',
    'Secome',
    'Segbeya',
    'Segbeya Akpoutouhoue',
    'Segbeya Amonle',
    'Segbeya Zoundome',
    'Segbohoue',
    'Segbohoue Assito',
    'Segbohoue Centre',
    'Telokoe-Ahouya',
    'Tokpa-Daho',
    'Tokpa-Dome',
    'Vovio',
    'Xwlacome',
    'Yeme',
  ],
  'Lalo': [
    'Aboti',
    'Adjacome',
    'Adjaglimey',
    'Adjaigbonou',
    'Adjassagon',
    'Adonou',
    'Adoukandji',
    'Affomai',
    'Ahodjinnako',
    'Ahomadegbe',
    'Ahouada',
    'Alloya',
    'Assogbahoue',
    'Azangbe',
    'Banigbe',
    'Bayekpa Centre',
    'Davihoue',
    'Djibahoun',
    'Dogouedeta',
    'Dolohoue',
    'Edah-Gbawlahoue',
    'Eguehoue',
    'Gbefandji',
    'Gnamame',
    'Gnigbandjime',
    'Gnizounme',
    'Gouloko',
    'Goveta',
    'Hagnonhoue',
    'Hangbannou',
    'Hazin',
    'Hehoukpa',
    'Helli',
    'Hlassame',
    'Kadebou',
    'Kaihoue',
    'Kindji',
    'Kingnenouhoue',
    'Klabessihoue',
    'Kondjon',
    'Koutchikanhoue',
    'Koutime',
    'Kowome',
    'Kpassakanme',
    'Kuivonhoue',
    'Lalo',
    'Lokogba',
    'Lokoli',
    'Lome',
    'Ouinfa',
    'Oukanme',
    'Sawanou',
    'Sewahoue',
    'Sohounouhoue',
    'Sowanouhoue',
    'Tandji',
    'Tchito',
    'Tohou',
    'Tohou-Centre',
    'Toulehoudji',
    'Wewehoue',
    'Yamontou',
    'Yobohoue',
    'Zalli',
    'Zonmondji',
    'Zoundjame',
    'Zoundotan',
    'Zounhome',
    'Zountokpa',
  ],
  'Lokossa': [
    'Ablode',
    'Adjakomey',
    'Adjigo-Kpodave',
    'Adjohoue',
    'Adrodji',
    'Adrogbo',
    'Agame',
    'Agnigbavedji',
    'Agnito',
    'Agnito-Tchicomey',
    'Agnivedji',
    'Agonkanme',
    'Agonve',
    'Ahotissa',
    'Ahouame',
    'Akodedjro',
    'Aligoudo',
    'Atikpeta',
    'Atinmado',
    'Azizossa',
    'Dansihoue',
    'Dekanme',
    'Dessa',
    'Djehadji',
    'Djondji-Zounme',
    'Doukonta',
    'Fongba',
    'Gandjazounme',
    'Ganwotissa',
    'Gbodedji',
    'Glo',
    'Guehounkon',
    'Guinkomey',
    'Hlodo',
    'Houanme',
    'Houedaho',
    'Houin',
    'Kessawe',
    'Kinwedji',
    'Koudo',
    'Kplogodome',
    'Kpota',
    'Lego',
    'Logbo',
    'Lokossa',
    'Medehounta',
    'Monkpa-Sedji',
    'Ouedeme-Adja',
    'Ouedeme-Cada',
    'Ouedeme-Djanglanme',
    'Sague',
    'Sedje-Gleta',
    'Sessehoukanme',
    'Takon-Zongo',
    'Tchicomey',
    'Tedeado',
    'Tinou',
    'Todoga',
    'Togueme',
    'Tokpa',
    'Tota-Kindji',
    'Totinga',
    'Tozounme',
    'Tozounme-Gbedji',
    'Veha',
    'Yenawa',
    'Zoungame',
    'Zounhoue',
  ],
  'Malanville': [
    'Bangou',
    'Baniloua',
    'Banite-Fere Kire',
    'Banite-Kouberi',
    'Bodjecali',
    'Bodjecali-Chateau',
    'Boiffo',
    'Degue-Degue',
    'Djindegabi-Tounga',
    'Fiafounfoun',
    'Gaabo',
    'Galiel',
    'Garou',
    'Garou-Beri',
    'Garou-Tedji',
    'Garou-Tedji-Gorobani',
    'Garou-Wenou-Kannin',
    'Godjekoara',
    'Golobanda',
    'Gorou-Djinde',
    'Goroussoundougou',
    'Goun-Goun',
    'Guene',
    'Guene-Guidigo',
    'Guene-Zerme',
    'Illoua',
    'Issene',
    'Kambouwo-Tounga',
    'Kantoro',
    'Kassa',
    'Koara-Tedji',
    'Kotchi',
    'Koualerou',
    'Kouara-Tedji',
    'Lakali-Kaney',
    'Madecali',
    'Madecli-Zongo',
    'Malanville',
    'Melayakouara',
    'Mokolle',
    'Molla',
    'Monkassa',
    'Sakawan-Tedji',
    'Sakawan-Zenon',
    'Santche',
    'Sende',
    'Sounbey-Gorou',
    'Tassi-Djinde',
    'Tassi-Tedji',
    'Tassi-Tedji-Banizounbou',
    'Tassi-Tedji-Boulanga',
    'Tassi-Zenon',
    'Tondi-Banda',
    'Toro-Zougou',
    'Toumboutou',
    'Tounga-Tedji',
    'Wanda',
    'Wanzam-Koara',
    'Wollo',
    'Wollo-Chateau',
    'Wouro-Yesso',
  ],
  'Materi': [
    'Bahoun',
    'Bampora',
    'Bogodori',
    'Borifieri',
    'Bourporga',
    'Boutouhounpingou',
    'Coupiani',
    'Dabogohoun',
    'Dassari',
    'Doga',
    'Fehoun',
    'Fekerou',
    'Firihoun',
    'Gouande',
    'Holli',
    'Kandeguehoun',
    'Kandjo',
    'Kankini-Seri',
    'Koneandri',
    'Kotari',
    'Kouantieni',
    'Kouarhoun',
    'Kouforpissiga',
    'Koundri',
    'Kourou-Koualou',
    'Koussega',
    'Koutoukondiga',
    'Kperehoun',
    'Madoga',
    'Mahontika',
    'Materi',
    'Merhoun',
    'Mihihoun',
    'N\'tchiega',
    'Nagassega',
    'Nagassega-Kani',
    'Nambouli',
    'Niehoun-Laloga',
    'Nodi',
    'Nouari',
    'Ouriyori',
    'Pingou',
    'Porga',
    'Pouri',
    'Pourniari',
    'Sakonou',
    'Sekanou',
    'Setchindika',
    'Sindori-Toni',
    'Souomou',
    'Tambogou-Kondri',
    'Tampanga',
    'Tampinti-Yerou',
    'Tampoure-Pogue',
    'Tanhoun',
    'Tankouari',
    'Tankouayokouhoun',
    'Tantega',
    'Tantouri',
    'Tassahoun',
    'Tchanhouncossi',
    'Tcharikouanga',
    'Tchassaga',
    'Tebiwogou',
    'Tetonga',
    'Tiari',
    'Tigninga',
    'Tihoun',
    'Tintonsi',
    'Tinwega',
    'Toubougnini',
    'Toussari',
    'Yanga',
    'Yansaga',
    'Yedekahoun',
    'Yondisseri',
    'Yopiaka',
  ],
  'N\'dali': [
    'Alafiarou',
    'Angaradebou',
    'Banhoun',
    'Banhoun-Gando',
    'Banhoun-Kpo',
    'Binassi',
    'Bio-Sika',
    'Boko',
    'Bori',
    'Bori-N\'darnon',
    'Bori-Peulh',
    'Bounin',
    'Bouyerou',
    'Dabou',
    'Dankourou',
    'Darnon',
    'Darnon-Gourou',
    'Douroube',
    'Gah Alerou',
    'Gah-Sankounin',
    'Gah-Winra',
    'Gandou-Nomba',
    'Gbegourou',
    'Gbeguina',
    'Gbitebou',
    'Gounin',
    'Guessou',
    'Kakara',
    'Keri',
    'Komiguea',
    'Kori',
    'Mareborou',
    'Maregourou',
    'Maregourou-Peulh',
    'Moussoukoure',
    'N\'dali',
    'N\'dali-Peulh',
    'Ouenou',
    'Ouenou-Peulh',
    'Pourampare',
    'Sakarou',
    'Samounin',
    'Sinawourarou',
    'Sinisson',
    'Sirarou',
    'Sonnoumon',
    'Sonnoumon-Gando',
    'Sonnoumon-Peulh',
    'Souarou',
    'Suanin',
    'Tamarou',
    'Teme',
    'Teme-Peulh',
    'Tepa',
    'Tinre',
    'Tounre',
    'Treboun',
    'Wari-Goura',
    'Warikpa',
    'Wereke',
    'Woasson',
    'Wobakarou',
    'Yankoi',
    'Yeroumarou',
  ],
  'Natitingou': [
    'Bagri',
    'Bangretamou',
    'Berecingou',
    'Bokoro',
    'Boriyoure',
    'Dassakate',
    'Didapoumbor',
    'Dikouan',
    'Ditawan',
    'Djindjire-Beri',
    'Dokonde',
    'Doyakou',
    'Fayoure',
    'Gnagnammou',
    'Kampouya',
    'Kantaborifa',
    'Kantchagoutamou',
    'Katanginka',
    'Koka',
    'Kota-Monnongou',
    'Kotopounga',
    'Kouaba',
    'Kouandata',
    'Kouatidabirgou',
    'Koubirgou',
    'Koudengou',
    'Kouetena',
    'Koukouabirgou',
    'Kounadorgou',
    'Kounapeigou',
    'Kounitchangou',
    'Koupeico',
    'Koussantikou',
    'Koussigou',
    'Koutanongou',
    'Koutie',
    'Koutie Tchatido',
    'Kouwa N\'pongou',
    'Kouwanwangou',
    'Moupemou',
    'Moussansamou',
    'Natitingou I',
    'Natitingou Ii',
    'Natitingou Iii',
    'Onsikoto',
    'Ourbouga',
    'Ourkparbou',
    'Ouroubonna',
    'Pam-Pam',
    'Peporiyakou',
    'Perma',
    'Perma Centre',
    'Pouya',
    'Santa',
    'Sinaicire',
    'Sountchirantikou',
    'Souroukou',
    'Tagahei',
    'Takonta',
    'Tampedema',
    'Tchantangou',
    'Tchirimina',
    'Tchoumi-Tchoumi',
    'Tedonte',
    'Tenounkonte',
    'Tepente',
    'Tetante',
    'Tignanpeti',
    'Tigninti',
    'Tikouani',
    'Tipeti',
    'Toroubou',
    'Wetipounga',
    'Wimmou',
    'Winke',
    'Yakpangoutingou',
    'Yarikou',
    'Yetapo',
    'Yimporima',
    'Yokossi',
  ],
  'Nikki': [
    'Alafiarou',
    'Angankirou',
    'Baani',
    'Bantere',
    'Barkedje',
    'Barougouroussi',
    'Belle',
    'Biro',
    'Boo',
    'Boukanere',
    'Chein-Daroukpara',
    'Chein-Tasso',
    'Dannon',
    'Danri',
    'Daroukpara',
    'Deman',
    'Donkparawi',
    'Fo-Darou',
    'Fombawi',
    'Gah-Maro',
    'Gah-Maro-Peulh',
    'Gan-Gberou',
    'Ganchon',
    'Ganrou',
    'Ganrou-Peulh',
    'Gbabire',
    'Gbaoussi',
    'Gbaoussi-Kpaa',
    'Gbari',
    'Gbegourou',
    'Gnanhoun',
    'Gnelkiradje',
    'Gnelsanda',
    'Gneltoko',
    'Gnonkourakali',
    'Gnonkourokali',
    'Gore',
    'Gori',
    'Gossogui-Gourebata',
    'Gotel',
    'Goure Baba',
    'Goure-Gbata',
    'Gourou',
    'Gourou-Pibou',
    'Guema',
    'Guidandole',
    'Guinrou',
    'Guinrou-Peulh',
    'Kali',
    'Kassapere',
    'Koni',
    'Koussoukou',
    'Kparisserou',
    'Kpawolou',
    'Kpebourabou',
    'Maro',
    'Massiagourou',
    'Monnon',
    'Moussoure',
    'Nallou',
    'Nikki',
    'Ningouarou',
    'Ouenou',
    'Ouenou-Nikki',
    'Ouenra-Peulh',
    'Ourarou',
    'Ouroumon',
    'Ouroumonsi-Peulh',
    'Sakabansi',
    'Sansi',
    'Serekali',
    'Serekali-Baka',
    'Serewondirou',
    'Sinangourou',
    'Sonsonre',
    'Sonwore',
    'Soubo-Baraworou',
    'Soubo-Ganderou',
    'Soumarou',
    'Suya',
    'Takou',
    'Tanakpe',
    'Tasso',
    'Tchicandou',
    'Tebo',
    'Tepa',
    'Tontarou',
    'Tontarou-Peulh',
    'Totorou',
    'Weketere',
    'Wonko',
    'Woroumangassarou',
    'Yako-Kparou',
    'Yao-Gourou',
    'Yorarou',
  ],
  'Ouake': [
    'Adedewo',
    'Adjede',
    'Agbandare',
    'Ague-Garba',
    'Akoussite',
    'Akpade',
    'Alayomde',
    'Alitokoum',
    'Assarade',
    'Assode',
    'Atchakitam',
    'Atchankomou',
    'Atchankpa-Kolah',
    'Awanla',
    'Awotobi',
    'Badjoude',
    'Baparapei',
    'Bissetougou',
    'Bohomdo',
    'Daka',
    'Gao',
    'Gbaou',
    'Gnalo',
    'Gnangba Kabia',
    'Itchelli',
    'Itchode',
    'Kadolassi',
    'Kagnifele',
    'Kakpala',
    'Kakpessia',
    'Kante',
    'Kassua-Alla',
    'Kawado',
    'Kim-Kim',
    'Komde',
    'Komtcha',
    'Koubly',
    'Koukoulounda',
    'Kpakpalare',
    'Kpeli-Fada',
    'Kpelite',
    'Kpeloude',
    'Landa',
    'Madjatom',
    'Mami',
    'Mankpassi',
    'N\'djakada',
    'Ouake',
    'Ouramare',
    'Pamou',
    'Semere 1',
    'Semere 2',
    'Sobite',
    'Sonaholou',
    'Sonate',
    'Talinta',
    'Tchalade',
    'Tchalinga',
    'Tchingayare',
    'Tchitchakou',
    'Troucare-Bas',
    'Wakite',
    'Wekete',
    'Yamsale',
  ],
  'Ouassa-Pehunco': [
    'Bana',
    'Beket',
    'Beket-Gah',
    'Bonigourou',
    'Boude',
    'Bouerou',
    'Doh',
    'Gambinou',
    'Gbeba',
    'Gnemasson',
    'Gnemasson-Gando',
    'Gonri',
    'Gountia',
    'Guimbererou',
    'Mare Orou Gah',
    'Nassou',
    'Ningoussourou',
    'Ouassa-Kika',
    'Ouassa-Maro',
    'Pehonco-Tatapouranou',
    'Pehunco',
    'Pehunco I',
    'Pehunco Ii',
    'Pehunco-Gah',
    'Sayakrou',
    'Sayakrou - Gah',
    'Sinaou',
    'Sinaourarou',
    'Sinaourarou-Gah',
    'Soaodou',
    'Soassararou',
    'Somparerou-Gah',
    'Tobre',
    'Tonri',
    'Wakarou',
    'Wokou',
  ],
  'Ouesse': [
    'Adougou',
    'Adougou-Agah',
    'Affessomou',
    'Agboro-Idouya',
    'Agboro-Kombon',
    'Akpero',
    'Anseke',
    'Attannondoho',
    'Attata',
    'Ayedero',
    'Ayetoro',
    'Azraou',
    'Botti',
    'Botti-Houegbo',
    'Challa-Ogoi',
    'Challa-Ogoi Alougbede',
    'Challa-Ogoi Guedon',
    'Djegbe',
    'Djegbe-Lokossa',
    'Djegbe-Odjaha',
    'Dokoundoho',
    'Ekpa',
    'Evai-Gbaffo',
    'Gbanlin',
    'Gbanlin-Aizon',
    'Gbede',
    'Gbeme',
    'Idadjo',
    'Ikemon',
    'Ikemon-Ewonda',
    'Ikemon-Ewontoutou',
    'Kilibo',
    'Kilibo-Adjougou',
    'Kilibo-Gare',
    'Kilibo-Olata',
    'Kokoro Awoyo',
    'Kokoro Centre',
    'Kpassa',
    'Lakoko',
    'Laminou',
    'Laminou-Aidjedo',
    'Malete',
    'N\'gbehouedo',
    'N\'gbehouedo-Routo',
    'Odo-Akaba',
    'Odougba',
    'Ogbe',
    'Ogoutedo',
    'Ohoula',
    'Olouni-N\'gbe',
    'Ouesse',
    'Ouesse Centre',
    'Ouesse-Aizon',
    'Owolafe',
    'Suru-Lere',
    'Tchedjannangnon',
    'Tosso',
    'Toui',
    'Toui-Gare',
    'Toui-Odelakou',
    'Toui-Odjoule',
    'Toui-Pk',
    'Vodje',
    'Vossa',
    'Wodji',
    'Wokpa',
    'Yaoui',
    'Zogba-Gaou',
    'Zogba-Trekou',
  ],
  'Ouidah': [
    'Abatta',
    'Acadjame',
    'Adjohoundja-Monso',
    'Adjra-Adovie',
    'Adjra-Hounve',
    'Adounko',
    'Adounko Ayignon',
    'Agbadjihonto',
    'Agbanlindjehoue',
    'Agbanou',
    'Agbanzin-Kpota',
    'Agbanzin-Kpota Zounvlame',
    'Agbessikpe Djika',
    'Agouin',
    'Ahouandji',
    'Ahouandjigo',
    'Ahouicodji',
    'Ahozon',
    'Aido',
    'Amoulehoue',
    'Assogbenou-Daho',
    'Avlekete',
    'Azizakoue',
    'Bossouvi',
    'Dangbehoue',
    'Degoue',
    'Dekouenou',
    'Djegbadji',
    'Djegbame',
    'Djondji',
    'Docomey',
    'Fonkounme',
    'Fonsrame',
    'Gakpe',
    'Ganve',
    'Gbehonou',
    'Gbena-Nord',
    'Gbena-Sud',
    'Gbeto-Nord',
    'Gbeto-Sud',
    'Gbezounme',
    'Gomey',
    'Hehounli',
    'Hio',
    'Hio Vinawa',
    'Houakpe-Daho',
    'Houedjedo',
    'Houeyiho',
    'Houndjava',
    'Hounhanmede',
    'Kouvenanfide',
    'Kpasse',
    'Kpovie',
    'Lebou Alafia',
    'Lebou Campto',
    'Meko',
    'Minantinkpon',
    'Oke-Agbede',
    'Ouesse',
    'Ouidah I',
    'Ouidah Ii',
    'Ouidah Iii',
    'Ouidah Iv',
    'Pahou',
    'Pahou Centre',
    'Savi',
    'Savi-Houeton',
    'Selloli-Bazounkpa',
    'Seyigbe',
    'Sogbadji',
    'Tohonou',
    'Toligbe',
    'Tove Kpassezounto',
    'Tove Zobeto',
    'Vasseho',
    'Wagniho',
    'Womey',
    'Yamadjako',
    'Zomai',
    'Zomai-Kpota',
    'Zongo Malecome',
    'Zoungbodji Centre',
    'Zoungoudo',
  ],
  'Ouinhi': [
    'Adame',
    'Adogon',
    'Agonkon',
    'Ahicon',
    'Ahogo',
    'Aize',
    'Akante Zaloko',
    'Akante Zoungo',
    'Akassa',
    'Allabande',
    'Bossa Kpota',
    'Bossa Togoudo',
    'Dasso',
    'Dokodji',
    'Dolivi',
    'Gakou',
    'Gangban',
    'Ganhounme',
    'Gbokpago',
    'Gnanli',
    'Hinvedo',
    'Holli',
    'Houaidja',
    'Houanve',
    'Houedja',
    'Hounnoume',
    'Ilaka-Ozokpodji',
    'Kinsodji',
    'Kolly-Houssa',
    'Manfougbon',
    'Midjannangnan',
    'Monzoungoudo',
    'Odja-Idossou',
    'Ouinhi Centre',
    'Ouokon-Ahlan',
    'Ouokon-Zoungome',
    'Oussa',
    'Sagon',
    'Tannou',
    'Tevedji',
    'Tohoues',
    'Tozoungo',
    'Yaago',
    'Zoungue',
  ],
  'Parakou': [
    '1er Arrondissement',
    '2eme Arrondissement',
    '3eme Arrondissement',
    'Agba Agba',
    'Alaga',
    'Albarika',
    'Amanwignon',
    'Assagbinin Baka',
    'Bakinkoura',
    'Bakounourou',
    'Bakperou',
    'Banikanni',
    'Banikanni-Douwerou',
    'Banikanni-Eni',
    'Banikanni-Madjatom',
    'Baparape',
    'Beyarou',
    'Bosso-Camps-Peulhs',
    'Boundarou',
    'Camp-Adagbe',
    'Damagourou',
    'Depot',
    'Dokparou',
    'Gaanon',
    'Gah',
    'Ganou',
    'Gbira',
    'Goromosso',
    'Gounin',
    'Guema',
    'Kabassira',
    'Kadera',
    'Korobororou',
    'Korobororou-Peulh',
    'Kpebie',
    'Kperou-Guera',
    'Ladjifarani',
    'Ladjifarani-Petit Pere',
    'Lemanda',
    'Madina',
    'Monnon',
    'Nikkikperou',
    'Nima-Sokounon',
    'Oueze',
    'Rose-Croix Bah Mora',
    'Sawararou',
    'Sinagourou',
    'Sourou',
    'Swinrou-Kpassagambou',
    'Thian',
    'Titirou',
    'Tourou-Dispensaire',
    'Tourou-Palais-Royal',
    'Tranza',
    'Wansirou',
    'Wore',
    'Worou-Tokorou',
    'Woubekou-Gah',
    'Zazira',
    'Zongo',
    'Zongo-Zenon',
  ],
  'Perere': [
    'Alafiarou',
    'Assagnahoun',
    'Bani-Peulh',
    'Banigourou',
    'Bawera',
    'Berekoudo',
    'Boherou',
    'Bokerou',
    'Bonrou',
    'Bonrou-Gando',
    'Borikirou',
    'Boro',
    'Bougnankou',
    'Bougnerou',
    'Diguidirou',
    'Diguidirou-Peulh',
    'Gah-Maro',
    'Gando-Alafiarou',
    'Gbamon',
    'Gbande',
    'Gninsy',
    'Gninsy-Gando',
    'Gninsy-Peulh',
    'Gommey',
    'Gorobani',
    'Gounkpare',
    'Guinagourou',
    'Guinagourou-Peulh',
    'Guinro',
    'Kabadou',
    'Koukoumbou',
    'Kousso',
    'Kpawolou',
    'Kpebie',
    'Kpebie-Gando',
    'Nanin',
    'Nassy',
    'Nassy-Gando',
    'Nima-Beri',
    'Ogamoin',
    'Ourarou',
    'Pane',
    'Pane-Guea',
    'Perere',
    'Perere-Gourou',
    'Perere-Peulh',
    'Sakparou',
    'Sandilo',
    'Sandilo-Gando',
    'Sanrekou',
    'Sinanimoin',
    'Sombirikperou',
    'Sonon',
    'Sontou',
    'Soria',
    'Soubado',
    'Taberou',
    'Tchori',
    'Tisserou',
    'Wokparou',
    'Won',
    'Wondou',
    'Worokpo',
  ],
  'Pobe': [
    'Abba',
    'Adjegounle',
    'Adjissou',
    'Agbele',
    'Ahoyeye',
    'Akouho',
    'Akpaman',
    'Akpate',
    'Atchaga',
    'Ayere-Agbarou',
    'Ayetedjou',
    'Banigbe',
    'Chaffou',
    'Eguelou',
    'Gbanago',
    'Ibate',
    'Idi-Oro',
    'Idogan',
    'Iga',
    'Igana',
    'Igbidi',
    'Igbo-Assogba',
    'Igbo-Ede',
    'Igbo-Ewe',
    'Igbo-Ocho',
    'Igboiche',
    'Igbokofin-Eguelou',
    'Ihoro',
    'Illekpa',
    'Illemon',
    'Illoulofin',
    'Illoussa-Ossomou',
    'Issaba',
    'Issale-Affin Douane',
    'Issale-Affin Ii',
    'Issale-Ibere',
    'Ita-Adeleye',
    'Ita-Atinga',
    'Itchagba',
    'Itchakpo',
    'Itchede',
    'Itcheko',
    'Itchoche',
    'Iwoye',
    'Kadjola',
    'Ketty',
    'Lafenwa',
    'Mamague',
    'Ogouba',
    'Oke Ata',
    'Oke Ola',
    'Oke-Ita',
    'Onigbolo',
    'Otekotan',
    'Ouignan-Ile',
    'Pobe',
    'Pobe-Nord',
    'Talala',
    'Towe',
  ],
  'Porto-Novo': [
    '1er Arrondissement',
    '2eme Arrondissement',
    '3eme Arrondissement',
    '4eme Arrondissement',
    '5eme Arrondissement',
    'Accron-Gogankomey',
    'Adjegounle',
    'Adjina Nord',
    'Adjina Sud',
    'Adomey',
    'Agbokou Aga',
    'Agbokou Bassodji Mairie',
    'Agbokou Centre Social',
    'Agbokou Odo',
    'Ahouantikomey',
    'Akonaboe',
    'Akpassa Odo Oba',
    'Anavie',
    'Anavie Voirie',
    'Attake Olory-Togbe',
    'Attake Yidi',
    'Avakpa Kpodji',
    'Avakpa-Tokpa',
    'Avassa Bagoro Agbokomey',
    'Ayetoro',
    'Ayimlonfide',
    'Deguekome',
    'Djassin Daho',
    'Djassin Zounme',
    'Djegan Daho',
    'Djegan Kpevi',
    'Djlado',
    'Dodji',
    'Donoukin Lissessa',
    'Dota-Attingbansa-Azonzakomey',
    'Dowa',
    'Dowa Aliogbogo',
    'Dowa Dedome',
    'Foun-Foun Djaguidi',
    'Foun-Foun Gbego',
    'Foun-Foun Sodji',
    'Foun-Foun Tokpa',
    'Ganto',
    'Gbassou-Itabodo',
    'Gbecon',
    'Gbedjromede Fusion',
    'Gbezounkpa',
    'Gbodje',
    'Guevie',
    'Guevie Djeganto',
    'Guevie-Zinkomey',
    'Hassou Ague',
    'Hinkoude',
    'Hlogou Ou Hlongou',
    'Hondji-Honnou Filla',
    'Houegbo-Hlinkomey',
    'Houeyogbe-Gbedji',
    'Houezounmey',
    'Houinme Chateau D\'eau',
    'Houinme Djaguidi',
    'Houinme Ganto',
    'Houinme Gbedjromede',
    'Houinvie',
    'Hounsa',
    'Hounsouko',
    'Idi-Araba',
    'Ilefie',
    'Kandevie Missogbe',
    'Kandevie Owode',
    'Kandevie Radio Hokon',
    'Koutongbe',
    'Kpogbonme',
    'Kpota Sandodo',
    'Lokossa',
    'Louho',
    'Oganla Atakpame',
    'Oganla Nord',
    'Oganla Poste',
    'Oganla Soke',
    'Oganla Sud',
    'Oganla-Gare-Est',
    'Ouando',
    'Ouando Clekanme',
    'Ouando Kotin',
    'Ouinlinda Aholoukomey',
    'Ouinlinda Hopital',
    'Sadognon-Adjegounle',
    'Sadognon-Woussa',
    'Sagbo Kossoukode',
    'Sedjeko',
    'Seto - Gbodje',
    'Sokomey-Toffinkomey',
    'Tchinvie',
    'Togoh - Adankomey',
    'Tokpota Dadjrougbe',
    'Tokpota Davo',
    'Tokpota Vedo',
    'Tokpota Zebe',
    'Tokpota Zinlivali',
    'Vekpa',
    'Zebou -Itatigri',
    'Zebou -Masse',
    'Zebou Aga',
    'Zebou Ahouangbo',
    'Zounkpa Houeto',
  ],
  'Sakete': [
    'Adanmayi',
    'Adjegounle',
    'Adjohoun-Kolle',
    'Adjohoun-Kolledjedje',
    'Agada-Hounme',
    'Agonsa',
    'Aguidi',
    'Akadja',
    'Akpechi',
    'Araromi',
    'Aribidessi',
    'Assa-Game',
    'Assa-Idioche',
    'Attan Okouta-Kadjola',
    'Attan-Onibedji',
    'Attewo Lara',
    'Ayetoro Oke Awo',
    'Ayidjedo',
    'Ayita',
    'Barigbo-Owode',
    'Dagbao',
    'Degoun',
    'Degue',
    'Djoko',
    'Dra',
    'Gbagla Nounagnon',
    'Gbagla-Yovogbedji',
    'Gbokoudai',
    'Gbougbouta',
    'Gbozounmon',
    'Houegbo',
    'Hounme',
    'Ibadja Sodji',
    'Idjiboro',
    'Igba',
    'Igbo Egan',
    'Igbo-Abikou',
    'Igbo-Akpa',
    'Igbo-Assan',
    'Igbo-Eye',
    'Igbola',
    'Ikemon',
    'Ikpedjile',
    'Illako Faadji-Ita Akpinty',
    'Illako Idioro',
    'Illasso Nagot',
    'Illasso Saharo',
    'Illoro Aguidi',
    'Illougou-Kossomi',
    'Issale Eko',
    'Ita Alabe',
    'Ita Gbokou',
    'Ita Oro-Irede',
    'Ita-Ayinla',
    'Ita-Djebou',
    'Iwere',
    'Kadjola',
    'Kobedjo',
    'Kologbo Meke',
    'Kossi',
    'Makpa',
    'Makpohou',
    'Miroko',
    'Modogan',
    'Moro',
    'Odanregoun',
    'Odanyogoun',
    'Odella',
    'Oke',
    'Okeigbo',
    'Saharo Djedje',
    'Saharo Nagot',
    'Sakete 1',
    'Sakete 2',
    'Sanrin-Kpinle',
    'Sodji',
    'Suru Lere',
    'Takon',
    'Takon Centre',
    'Tota',
    'Wai',
    'Yogou Tohou',
    'Yoko',
    'Yoko Centre',
    'Zimon',
  ],
  'Savalou': [
    'Aballa',
    'Abeokouta',
    'Abiadji-Sogoudo',
    'Adjegounle',
    'Adjoya',
    'Affe Zongo',
    'Agah',
    'Agbodranfo',
    'Agbomadin',
    'Aglamidjodji',
    'Agonmey',
    'Ahito',
    'Ahossedo',
    'Akete',
    'Akpaki',
    'Alle',
    'Alloudi-Goure',
    'Amou',
    'Amou Sakaou',
    'Anigbe',
    'Arounde',
    'Attakplakanme',
    'Awiankanme',
    'Azonkangoudo',
    'Bame',
    'Bebiani',
    'Codji',
    'Coffe Agballa',
    'Covedji',
    'Dagadoho',
    'Dame',
    'Djabigon',
    'Djalloukou',
    'Djallouma',
    'Djantadoho',
    'Djime',
    'Dodomey',
    'Doissa Honnoukon',
    'Doissa Sokpa',
    'Doume',
    'Doume Lakoun',
    'Dozoundji',
    'Ekpa',
    'Felma',
    'Gbaffo Dogoudo',
    'Gbaffo Houegbo',
    'Gbaglodji',
    'Gobada',
    'Govi',
    'Honnoukon',
    'Idjou',
    'Igberi',
    'Iroukou',
    'Issale',
    'Kadjotche',
    'Kaman',
    'Kannahoun',
    'Kitikpli',
    'Klougo',
    'Koffodoua',
    'Kokoro',
    'Konkondji',
    'Koutago',
    'Kpakpassa',
    'Kpakpavissa',
    'Kpataba',
    'Kpekpelou',
    'Lahotan',
    'Lama',
    'Leke',
    'Lekpa',
    'Lema',
    'Logbo',
    'Logozohe',
    'Loukintowin',
    'Lowo',
    'Lowozoungo',
    'Lozin',
    'Makinnou',
    'Medetekpo',
    'Miniki',
    'Misse',
    'Mondji',
    'Monfio',
    'Monkpa',
    'Moussoungo',
    'N\'dasso',
    'N\'gbehan',
    'Naoudji',
    'Obicro',
    'Odo-Agbon',
    'Okouffo',
    'Olouwakemi',
    'Ottele',
    'Ottola',
    'Ouesse',
    'Savalou-Aga',
    'Savalou-Agbado',
    'Savalou-Attake',
    'Segbeya',
    'Segui',
    'Sohedji',
    'Sozoume',
    'Tchetti',
    'Tchogodo',
    'Walla',
    'Zadowin',
    'Zankpe-Houessinhoue',
    'Zomakidji',
    'Zongo',
    'Zongo-Albarika',
    'Zoukpa',
    'Zoundji',
    'Zouzonkanme',
  ],
  'Save': [
    'Adido',
    'Adjegoule',
    'Agbaboue',
    'Agbadjo',
    'Agbaigodo',
    'Akon',
    'Alafia',
    'Atchakpa',
    'Atchakpa-Kpingni',
    'Atesse',
    'Atti',
    'Awo Seriki',
    'Ayedjoko',
    'Baako',
    'Babaguidai',
    'Banigbe',
    'Besse',
    'Besse Owode',
    'Boni',
    'Boubouhou',
    'Dakpa',
    'Dani',
    'Depot Centre',
    'Diho-Agbongui',
    'Diho-Ogbo',
    'Djabata',
    'Djaloumon',
    'Djangbe',
    'Eetou',
    'Etiofe',
    'Fatchodjonin',
    'Gah Akeekee',
    'Gbere',
    'Gobe',
    'Gogoro',
    'Igbodja',
    'Igboe',
    'Issale Otin',
    'Iwee',
    'Kaboua',
    'Kadjogbe',
    'Kadjola',
    'Kilibo-Ogbo',
    'Kingoun',
    'Kpabai',
    'Madina',
    'Monka',
    'Montewo',
    'Offe',
    'Oke Olou-Ossin',
    'Oke Olou-Otin',
    'Oke Owo',
    'Oke Owo-Aga',
    'Okounfo',
    'Okpa',
    'Okpara',
    'Ouoghi-Centre',
    'Ouoghi-Gare',
    'Ouoghi-Titon',
    'Plateau',
    'Sakin',
    'Sandehou',
    'Save-Nouveau',
    'Tchayagbangba',
    'Tchintchin',
    'Tchougbe',
    'Tchoui',
    'Zongo',
  ],
  'Segbana': [
    'Batazi',
    'Bedafou',
    'Bobena',
    'Boumoussou',
    'Diapeou',
    'Fondo',
    'Gandoloukassa',
    'Gbarana',
    'Gbasse',
    'Gbekakarou',
    'Gbessaka',
    'Gbessare',
    'Goungbe',
    'Guene Kouzi',
    'Guenelaga',
    'Kamanan',
    'Kambara',
    'Korowi',
    'Koute',
    'Kpassana',
    'Lete',
    'Libante',
    'Liboussou',
    'Limafrani',
    'Lougou',
    'Mafouta-Waassare',
    'Morou',
    'Niambara',
    'Piami',
    'Poela',
    'Samtimbara',
    'Saonzi',
    'Segbana',
    'Serebani',
    'Serekibe',
    'Sinwan',
    'Sokotindji',
    'Tchakama',
    'Tounga-Issa',
    'Waranzi',
    'Zonzi',
  ],
  'Seme-Podji': [
    'Agbalilame',
    'Agblangandan',
    'Agongo',
    'Agonsa Gbo',
    'Ahlome',
    'Aholouyeme',
    'Akpokpota',
    'Awanou',
    'Ayokpo',
    'Davatin',
    'Denou',
    'Dja',
    'Djeffa Glegbonou',
    'Djeffa Houedome',
    'Djeffa Houedome Gbago',
    'Djeffa Kowenou',
    'Djeho',
    'Djeregbe',
    'Djeregbe Houela',
    'Ekpe',
    'Ekpe Gbedjame',
    'Ekpe Kanhonnou',
    'Ekpe Wechindahome',
    'Ekpe-Kpecome',
    'Ekpe-Marina',
    'Ekpe-Pk10',
    'Ekpe-Seyive',
    'Gbakpodji',
    'Gbehonme',
    'Gbokpa',
    'Glogbo',
    'Glogbo Plage',
    'Goho',
    'Houeke',
    'Houinta',
    'Hovidokpo',
    'Kadjacome',
    'Ketonou',
    'Kpakpakanme',
    'Kpoguidi',
    'Krake-Daho',
    'Lokokoukoume',
    'Moudokome',
    'Okoun-Seme',
    'Podji-Ague',
    'Podji-Ague Gbago',
    'Podji-Misserete',
    'Sekandji',
    'Sekandji Allamandossi',
    'Sekandji Houeyogbe',
    'Seme-Podji',
    'Tchonvi',
    'Tchonvi Agbologoun',
    'Tohoue',
    'Torri-Agonsa',
    'Wegbego-Adieme',
  ],
  'Sinende': [
    'Bouro',
    'Diadia',
    'Didi',
    'Dombouri',
    'Fo-Bouko',
    'Fo-Boure',
    'Fo-Boure-Peulh',
    'Gah-Baka',
    'Gakperou',
    'Gamagui',
    'Gnanro-Baatonworou',
    'Gnanro-Gando',
    'Goro-Bani',
    'Goure-Guessou',
    'Gourou',
    'Gourou-Kperou',
    'Guessou-Bani',
    'Guessou-Bani-Peulh',
    'Haoussa',
    'Kossia',
    'Kparo',
    'Lemanou',
    'Monsi',
    'Narerou',
    'Sakarou',
    'Sekere',
    'Sekere-Gando',
    'Sekere-Maro',
    'Sekere-Peulh',
    'Seko-Kparou',
    'Serou',
    'Sikki',
    'Sikki-Gando',
    'Sikki-Gourou',
    'Sikki-Maro',
    'Sinende',
    'Sokka',
    'Sonkorou',
    'Toume',
    'Wari',
    'Wari-Gando',
    'Wari-Peulh',
    'Yarra-Bariba',
    'Yarra-Gando',
    'Yarra-Kouri',
    'Yarra-Peulh',
  ],
  'So-Ava': [
    'Agbongamey',
    'Agonmekomey',
    'Agoundankomey',
    'Ahomey Domey-Zounmey',
    'Ahomey-Fonsa',
    'Ahomey-Gbekpa',
    'Ahomey-Gblon',
    'Ahomey-Lokpo',
    'Ahomey-Lokpo Centre',
    'Ahomey-Ounmey',
    'Ahouanmongao',
    'Anaviecomey',
    'Aniankomey',
    'Assedokpa',
    'Avlezounmey',
    'Bessetonou',
    'Dakomey',
    'Dakomey-Yohonoukon',
    'Dekanmey',
    'Djekpe',
    'Dogodo',
    'Dokodji',
    'Domeguedji',
    'Dossougao',
    'Eguekomey',
    'Gansougbamey',
    'Ganvie 1',
    'Ganvie 2',
    'Ganviecomey',
    'Gbagbodji',
    'Gbamey-Tchewa',
    'Gbegbome Ouekekome',
    'Gbegodo',
    'Gbessou',
    'Gbetingao',
    'Gblonto',
    'Gounsoedji',
    'Gounsoegbamey',
    'Guedevie',
    'Guedevie-Gbegbessa',
    'Have',
    'Heni',
    'Hindagao',
    'Hlouazounmey',
    'Houedo-Aguekon',
    'Houndomey',
    'Hounhoue',
    'Kindji',
    'Kinto Ague',
    'Kinto Dokpakpa',
    'Kinto Oudjra',
    'Kpacomey',
    'Kpafe',
    'Kpassikomey',
    'Kpoviecomey',
    'Lokpodji',
    'Nonhoueto',
    'Sakomey',
    'Sindomey',
    'Sinhoungbomey',
    'So-Ava',
    'So-Chanhouetodo',
    'Sokomey',
    'Somai',
    'Tchinancomey',
    'Tohokomey',
    'Totakoun',
    'Vekky',
    'Vekky Daho',
    'Vekky Dogbodji',
    'Yokagao',
    'Zoungomey',
    'Zounhomey',
    'Zounkpode',
  ],
  'Tanguieta': [
    'Batia',
    'Biacou',
    'Bongou',
    'Bounta',
    'Bourgniessou',
    'Coroncore',
    'Cotiakou',
    'Daguimagninni',
    'Djidjire-Beri',
    'Dondongou',
    'Douani',
    'Finta',
    'Goro-Bani',
    'Hantekou',
    'Kayarika',
    'Kogniga',
    'Kotchekongou',
    'Kouayoti',
    'Kougnieri',
    'Koutchoutchougou',
    'Mamoussa',
    'Manougou',
    'Matanrgui',
    'N\'dahonta',
    'Nafayoti',
    'Nanebou',
    'Natagata',
    'Nigneri',
    'Nontingou',
    'Nowerere',
    'Ouankou',
    'Parabou',
    'Pemombou',
    'Penitingou',
    'Porhoum',
    'Porka',
    'Sammongou',
    'Sangou',
    'Sepounga',
    'Sonta',
    'Tahinkou',
    'Tahongou',
    'Taiacou',
    'Tanfere',
    'Tanguieta',
    'Tanongou',
    'Tapekou',
    'Tchaeta',
    'Tchafarga',
    'Tchatingou',
    'Tchawassaka',
    'Tchoutchoubou',
    'Tiele',
    'Tora',
    'Toriconcone',
    'Yangou',
    'Yarka',
    'Yehongou',
    'Yeyedi',
    'Youakou',
  ],
  'Tchaourou': [
    'Adamou-Kpara',
    'Agbassa',
    'Agramarou',
    'Akoundanmon',
    'Alafiarou',
    'Amadou-Kpara',
    'Atira-Kparou',
    'Ayegourou',
    'Babarou',
    'Badekparou',
    'Banigri',
    'Barerou',
    'Beterou',
    'Bonwouberou',
    'Boronin',
    'Borori',
    'Bouay',
    'Boukoussera',
    'Camp Zato',
    'Dagbara-Gourou',
    'Gah-Gourou',
    'Gah-Kpenou',
    'Gango',
    'Gararou',
    'Gbeba',
    'Gbekpanin',
    'Gbetebou',
    'Gbeyekerou',
    'Gokanna',
    'Gombouerou',
    'Goro',
    'Gouroubara',
    'Goussouambou',
    'Guinirou',
    'Kabo',
    'Kaki Koka',
    'Kassouala',
    'Kaya',
    'Kera',
    'Kika',
    'Kika-Barrage',
    'Kinnou-Kparou',
    'Koda',
    'Koko',
    'Kokobe',
    'Kontoubarou',
    'Koubou',
    'Kpakpanin',
    'Kpari',
    'Kpassa',
    'Kpassatona',
    'Kpawa',
    'Kpessou',
    'Kpewonkou',
    'Lafia-Bido',
    'Monrawonkourou',
    'Nannonrou',
    'Nim Souambou',
    'Oloungbe',
    'Ouberou',
    'Owode',
    'Sakana-Kpeba',
    'Sanson',
    'Sebou',
    'Sinahou',
    'Somou-Gah',
    'Sonna',
    'Soumon-Gah',
    'Sui-Gourou',
    'Tandou',
    'Tangue',
    'Tchalla',
    'Tchaourou',
    'Tchaourou-Gobi-Aledji',
    'Tchaourou-Issale',
    'Tchatchou',
    'Tchokpassi',
    'Tekparou',
    'Teou-Kpara',
    'Toko-Bio',
    'Toukossari',
    'Tourou-Souanre',
    'Warankperou',
    'Wari-Maro',
    'Winra',
    'Woria',
    'Worogui-Goura',
    'Yambouan',
    'Yebessi',
    'Yeroumarou',
  ],
  'Toffo': [
    'Abolou',
    'Aclonme',
    'Adjaho',
    'Adjakame',
    'Adjido',
    'Agaga',
    'Agahounkpokon',
    'Agbaga',
    'Agbame',
    'Agblome',
    'Agbotagon',
    'Agbozounkpa',
    'Agladokpa',
    'Agon',
    'Agonme',
    'Ague',
    'Ahlankpa',
    'Ahogbeme',
    'Aklissa',
    'Akpe',
    'Avissa',
    'Ayahonou',
    'Azonme',
    'Azonsa',
    'Badovita',
    'Bakanme',
    'Bossouvi',
    'Cassagbo',
    'Cogbo-Campement',
    'Colli',
    'Coussi',
    'Dame',
    'Dame Centre',
    'Dame-Gbedji',
    'Djanglanme',
    'Dogoudo',
    'Dolouvi',
    'Dome',
    'Dowa',
    'Fandji',
    'Ganme',
    'Gbede-Agonsa',
    'Gomey',
    'Gueme',
    'Helita',
    'Hessavi-Come',
    'Honli',
    'Houegbo',
    'Houegbo Tohome',
    'Houegbo-Gare',
    'Houegle',
    'Houenoussou',
    'Houngo-Dame',
    'Houngo-Gove',
    'Hounnouvie',
    'Hounyeme',
    'Kinzoun',
    'Koudjananko',
    'Kpokpa',
    'Kpome',
    'Kpozounme',
    'Lanhonnou',
    'Mazounkpa',
    'Niarin',
    'Sedessa Aligoudo',
    'Sedje',
    'Sedji',
    'Sehoue',
    'Sey',
    'Some',
    'Takon',
    'Toffo',
    'Toffo-Gare',
    'Togo',
    'Togoudo',
    'Togouin',
    'Vodje',
    'Yenawa',
    'Za',
    'Zeko',
    'Zimbenou',
    'Zohounkpo',
    'Zoundji',
    'Zoungame',
  ],
  'Tori-Bossito': [
    'Adjahassa',
    'Agazoun',
    'Agonkon',
    'Agouako',
    'Agueta',
    'Ahoueme',
    'Aidohoue',
    'Akadjame',
    'Anavie',
    'Avame',
    'Avame Centre',
    'Ayikinko',
    'Azohoue Cada Houngo',
    'Azohoue Cada Nord',
    'Azohoue Cada Sud',
    'Azohoue-Aliho',
    'Azohoue-Cada',
    'Azohoue-Cada Centre',
    'Azongo',
    'Bossito',
    'Denou',
    'Dohinonko',
    'Dokanme',
    'Dossou-Somey',
    'Fassinouhokon',
    'Gbedakonou',
    'Gbedewahoue',
    'Gbedjougo',
    'Gbegoudo',
    'Gbetaga',
    'Gbohoue',
    'Gbovie',
    'Hayakpa',
    'Hekandji',
    'Hetin-Yenawa',
    'Hla',
    'Honvie',
    'Houedaga',
    'Houngbagba',
    'Houngo',
    'Hounnonco',
    'Ketessa Agladji',
    'Kokanhoue',
    'Lokossa',
    'Maguevie',
    'Massetome',
    'Seigonme',
    'Sogbe',
    'Soklogbo',
    'Tandahota',
    'Tocoli',
    'Togoudo',
    'Tori-Bossito',
    'Tori-Cada',
    'Tori-Cada Centre',
    'Tori-Gare',
    'Tori-Gare Centre',
    'Wanho',
    'Zebe',
    'Zoungbome',
    'Zoungoudo',
    'Zounme',
    'Zounvessehou',
  ],
  'Toukountouna': [
    'Batitamou',
    'Boribansifa',
    'Bouyagnindi',
    'Datakou',
    'Dikokore',
    'Fatiya',
    'Kokokou',
    'Kokota',
    'Kouarfa',
    'Kouba',
    'Kpentikou',
    'Mako',
    'Mounoumborifa',
    'Moussitingou',
    'Nabaga',
    'Peperkou',
    'Takissari',
    'Tampatou',
    'Tampegre',
    'Tampobre',
    'Tandafa',
    'Tankokona',
    'Tantougou',
    'Tchakalakou',
    'Tchanhorta',
    'Tchoundekou',
    'Tectibayaou',
    'Toukountouna',
    'Wabou',
    'Wansokou',
  ],
  'Toviklin': [
    'Abloganme',
    'Adjido',
    'Adjido Centre',
    'Adjohoue',
    'Affomadi',
    'Agbedoume',
    'Agbozohoudji',
    'Agome',
    'Akome',
    'Atchioume',
    'Avedjin',
    'Awandji',
    'Ayidjedo',
    'Dandjekpohoue',
    'Dansouhoue',
    'Davi',
    'Dekandji',
    'Djidowanou',
    'Djigangnonhou',
    'Djikeme',
    'Djoudome',
    'Djouganme',
    'Djouvime',
    'Dohodji',
    'Doko',
    'Doko Atchanvigueme',
    'Doko Centre',
    'Doko Djoudome',
    'Gbayedji',
    'Gbinnouhoue',
    'Gboyizounhoue',
    'Glidji',
    'Hedjame',
    'Hewogbe',
    'Houedogli',
    'Houedogli Centre',
    'Houegangbe',
    'Houndehoussohoue',
    'Kleme',
    'Kodohoue',
    'Kpakouihoue',
    'Kpeve',
    'Kpodji',
    'Kpohoudjou',
    'Kpohoudjougan',
    'Lagbahome',
    'Lagbakada',
    'Maiboui Kpota',
    'Maiboui Sodokpohoue',
    'Missinko',
    'Missinko Centre',
    'Nanonme',
    'Natabouhoue',
    'Oussoume',
    'Sekouhoue',
    'Sognonnouhoue',
    'Tadokome',
    'Tannou Avedji',
    'Tannou-Gola',
    'Tannou-Gola Centre',
    'Tchankada',
    'Tchankoue',
    'Tchoulehoudji',
    'Tohounhoue',
    'Tossehoue',
    'Toviklin',
    'Toviklin Centre',
    'Toviklin Quartier',
    'Zaffi',
    'Zohenou',
    'Zohoudji',
    'Zougoume',
  ],
  'Za-Kpota': [
    'Adame',
    'Adaweme',
    'Adikogon',
    'Adjido',
    'Adjokan',
    'Adjoko',
    'Adovi',
    'Affossowogba',
    'Agbakou',
    'Agbogbomey',
    'Agbokpa',
    'Agondokpoe',
    'Agongbo',
    'Agonkanme',
    'Ahossougon',
    'Aitedekpa',
    'Akadjame',
    'Aketekpa',
    'Allahe',
    'Alligoudo',
    'Amlihohoue-Jardin',
    'Assanlin',
    'Dangbegon',
    'Dantota',
    'Davego',
    'Detekpa',
    'Djoitin',
    'Dogbanlin',
    'Dokpa',
    'Dotan',
    'Doutin',
    'Drame',
    'Folly',
    'Ganhoua',
    'Gnadokpa',
    'Hehounli',
    'Houangon',
    'Houanlikpa',
    'Houkanme',
    'Houngome',
    'Kemondji',
    'Keou',
    'Kodota',
    'Koguede',
    'Kpakpame',
    'Kpakpassa',
    'Kpokpoe',
    'Kpolokoe',
    'Kpozoun',
    'Lokoli',
    'Lontonkpa',
    'Mlinkpin-Guingnin',
    'Sogbelankou',
    'Sohoungo',
    'Sohounta',
    'Some',
    'Sowekpa',
    'Tangbe',
    'Tanta',
    'Togadji',
    'Yadin',
    'Yohoue',
    'Za-Aga',
    'Za-Hla',
    'Za-Kekere',
    'Za-Kpota',
    'Za-Tanta',
    'Za-Zounme',
    'Zeko',
    'Zoungoudo',
    'Zounzonme',
  ],
  'Zagnanado': [
    'Agbladoho',
    'Agongbodji',
    'Agonlin-Houegbo',
    'Agonve',
    'Ahlan',
    'Akohagon',
    'Assiangbome',
    'Ayogo',
    'Azakpa',
    'Bame',
    'Baname',
    'Dizigo',
    'Doga-Aga',
    'Doga-Alikon',
    'Doga-Dome',
    'Dohounme',
    'Don-Aliho',
    'Don-Tan',
    'Don-Tohome',
    'Dove',
    'Dovi',
    'Gbatezounme',
    'Gbonou',
    'Goblidji',
    'Houegbo-Aga',
    'Houegbo-Do',
    'Kingon',
    'Klobo',
    'Kpedekpo',
    'Kpoto',
    'Legbado',
    'Loko-Alankpe',
    'Massagbo',
    'N\'dokpo',
    'Sagbovi',
    'Sowe',
    'Tan-Adja',
    'Tan-Houegbo',
    'Tokplegbe',
    'Vodo',
    'Wometo',
    'Zagnanado',
    'Zagnanado Centre',
    'Zantan-Igbo-Ola',
    'Zingon',
    'Zonmon',
    'Zoungo-Wokpa',
    'Zoungoudo',
    'Zounnou',
  ],
  'Ze': [
    'Adjago',
    'Adjakpa',
    'Adjame',
    'Adjan',
    'Adjan-Gla',
    'Adjan-Houeta',
    'Adjrako',
    'Adohounsa',
    'Agbata',
    'Agbodjedo',
    'Agbohounsou',
    'Aglangbin',
    'Agondenou',
    'Agondotan',
    'Agongbo',
    'Agonzounkpa',
    'Agoundji',
    'Aguiakpa',
    'Ahouali',
    'Ahozonnoude',
    'Aifa',
    'Akadjame',
    'Akouedjromede',
    'Akpali',
    'Akpali-Do',
    'Akpalihonou',
    'Akpomey',
    'Anagbo',
    'Anavie',
    'Avlessa',
    'Awassou',
    'Awokpa',
    'Awonsedja',
    'Ayahounta-Fifadji',
    'Azonkanme',
    'Bodji',
    'Dawe',
    'Dawe-Centre',
    'Djigbe',
    'Djigbe-Ague',
    'Djigbe-Gbodje',
    'Djitin-Aga',
    'Djoko',
    'Dodji-Aga',
    'Dodji-Bata',
    'Dokota',
    'Dokota-Aga',
    'Dome-Seko',
    'Gandaho',
    'Gbagodo',
    'Gbeto-Fongbo',
    'Gbozounme',
    'Glegbodji Agah',
    'Glegbodji Do',
    'Gonfandji',
    'Goulo',
    'Guekoumede',
    'Havikpa',
    'Hekanme',
    'Houedazounkpa',
    'Houedota',
    'Houedota-Djoko',
    'Houegnonkpa',
    'Houehounta',
    'Houehounta-Tozounkpa',
    'Houeze',
    'Hounliko',
    'Hounsagoudo',
    'Hountakon',
    'Koudjannada-Tota',
    'Koundokpoe',
    'Kpatchame',
    'Mangassa',
    'Missebo',
    'Sedjannako',
    'Sedje-Denou',
    'Sedje-Houegoudo',
    'Sedje-Kpota',
    'Sedje-Zounmey-Aga',
    'Sessivali',
    'Sodji',
    'Tangbo',
    'Tangbo-Aga',
    'Tangbo-Do',
    'Tangnigbadji',
    'Tanmey',
    'Tanta',
    'Togbonou',
    'Togoudo',
    'Tomasseahoua',
    'Waga',
    'Wankon',
    'Wassa',
    'Wawata-Dandji',
    'Wawata-Zounto',
    'Wedjame',
    'Wedji',
    'Wo-Togoudo',
    'Yevi',
    'Yokpo',
    'Yokpo-Centre',
    'Zannoudji',
    'Zanzoun',
    'Ze',
    'Ze-Wedji',
    'Zoungbomey',
  ],
  'Zogbodomey': [
    'Aga',
    'Agadjaligbo',
    'Agblata',
    'Agoita',
    'Agouna',
    'Agrimey',
    'Ahouandjitome',
    'Ahoundome',
    'Akiza',
    'Alladaho',
    'Atchia',
    'Avannankanme',
    'Avavi',
    'Avlame',
    'Bognongnon',
    'Bolame',
    'Cana I',
    'Cana Ii',
    'Degueli',
    'Dehounta',
    'Deme',
    'Denou-Lissezin',
    'Djihizide',
    'Dodome',
    'Dogo',
    'Dogoudo',
    'Dohoue',
    'Dohounve',
    'Dome',
    'Dome-Go',
    'Don-Agonlin',
    'Don-Akadjame',
    'Don-Zoukoutoudja',
    'Dovogon',
    'Gandjekpindji',
    'Gbaffo',
    'Gbame',
    'Gbangnanme',
    'Gbedin',
    'Gohissanou',
    'Gome',
    'Gueme',
    'Hadagon',
    'Haya',
    'Hinzounme',
    'Hlagba-Denou',
    'Hlagba-Denou Atcha',
    'Hlagba-Lonme',
    'Hlagba-Ouassa',
    'Hlagba-Zakpo',
    'Hlanhonou',
    'Hon',
    'Kessedjogon',
    'Koto',
    'Kotokpa',
    'Koussoukpa',
    'Kpokissa',
    'Kpota',
    'Lokoli',
    'Male',
    'Massi',
    'Massi Alligoudo',
    'Ouassa',
    'Samionkpa',
    'Samionta',
    'Seme',
    'Tanwe-Hessou',
    'Tchiheigon',
    'Tegon',
    'Togbin',
    'Tohomey',
    'Tovlame',
    'Towe',
    'Yokon',
    'Zado-Adagon',
    'Zado-Gagbe',
    'Zalimey',
    'Zogbodomey',
    'Zogbodomey Centre',
    'Zoukou',
    'Zoungbo-Bogon',
    'Zoungbo-Zounme',
    'Zoungoudo',
  ],
};

/// Liste officielle des catégories de restaurants autorisées dans TrueAts.
/// Toute valeur hors de cette liste sera rejetée par le backend.
const List<String> kRestaurantCategories = [
  'Maquis',
  'Restaurant',
  'Fast-food',
  'Snack',
  'Buvette',
  'Café',
  'Bar',
  'Pâtisserie',
];
